### ISSUE TITLE
NoClassDefFoundError: org/intellij/plugins/hcl/HCLParser

### ISSUE THREAD

**Issue by hyzhak** [VladRassokhin/intellij-hcl#10]
just installed plugin to try it. And got this error once I have tried to open empty .hcl file

**Comment by VladRassokhin** [comment]
That's strange.
What product (IDEA,etc) and it version do you use?
Also info about OS and Java version would be nice.

**Comment by VladRassokhin** [comment]
And most important: Have you installed plugin from plugin repository? Or downloaded from github?

**Comment by SpencerBrown** [comment]
tried to reproduce, cannot make it fail, on plugin version 0.4.1, installed from plugin repo.

IntelliJ version 14.1.5, OS X 10.11.1, JRE 1.6.0-65 64-bit

**Comment by VladRassokhin** [comment]
@SpencerBrown Ok, thanks. Looks like @hyzhak downloaded sources zip from github and IDEA detected it as plugin (found plugin.xml)
