### ISSUE TITLE
Support git repo subfolders in module sources

### ISSUE THREAD

**Issue by mkuzmin** [VladRassokhin/intellij-hcl#100]
Module source can refer to a subdirectory inside a git repository, like `github.com/hashicorp/example//subdir`. 

At the moment the plugin does not support it, and reads variables from a top directory.
![image](https://user-images.githubusercontent.com/712402/29362875-56832edc-8296-11e7-90af-e4a5ba584545.png)

**Comment by VladRassokhin** [comment]
Already implemented in trunk, as noted on comments in #52
