### ISSUE TITLE
Plugin treats inner quotes as syntax errors

### ISSUE THREAD

**Issue by ninnemannk** [VladRassokhin/intellij-hcl#102]
When trying to use inner quotes inside of an interpolation block the plugin treats it as a syntax error. This functionality was added in [Terraform 0.7 as per this PR](https://github.com/hashicorp/hcl/pull/132). 

`stage     = "${replace("%{stageVariables.stage}", "%", "$")}"`

### Prerequisites
 - [√] Ensure you have latest version of plugin installed
 - [√] Search for possible issue duplicates

### Installation details
 - [√ ] IDE version 
```
IntelliJ IDEA 2017.1.5
Build #IU-171.4694.70, built on July 4, 2017
Subscription expired on August 24, 2017
JRE: 1.8.0_112-release-736-b21 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
```
 - [√] intellij-hcl plugin version
```
v0.6.5
```
 - [√] Terraform version
```
Terraform v0.10.2
```

### Terraform Configuration Files
```hcl
stage     = "${replace("%{stageVariables.stage}", "%", "$")}"
```

### Expected Behavior
Inner strings should be treated as such.

### Actual Behavior
The plugin treats the inner strings as syntax errors.

### Steps to Reproduce
Try to use inner strings inside of an interpolation block.

**Comment by VladRassokhin** [comment]
Fixed, would be available in next plugin update

**Comment by ninnemannk** [comment]
Great, thanks. Looking forward to the update.

**Comment by ishikin** [comment]
Hi Vlad! I think I ran into a variation of the same bug: getting "Missing closing quote" on
```"${replace("%{stageVariables.stage}", "\",\"", "$")}"```
Thanks!

**Comment by hameno** [comment]
I'm also getting a syntax error for this
```
resource "hcloud_ssh_key" "default" {
  name       = "Terraform"
  public_key = "${file("~/.ssh/id_rsa.pub")}"
}
```

![image](https://user-images.githubusercontent.com/365084/43684124-7c8733a6-989a-11e8-8f3b-19d640ff27da.png)

**Comment by VladRassokhin** [comment]
@hameno Please ensure that file has .tf extension or has language set to `Terraform Configuration`, not `Hashicorp Configuration Language` since in the latter injections are not allowed

**Comment by hameno** [comment]
Ahh, that fixed it. Terraform Config was only used for tfvars somehow
