### ISSUE TITLE
Terraform local values

### ISSUE THREAD

**Issue by johnsoft** [VladRassokhin/intellij-hcl#106]
Terraform now has syntax for [local values](https://www.terraform.io/docs/configuration/locals.html), introduced some time after v0.10.2. It'd be nice to have IDE support for them.

### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
IDE version:

```
PyCharm 2017.2.3 Build #PY-172.3968.37, built on September 1, 2017
JRE: 1.8.0_152-release-915-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

intellij-hcl plugin version: `0.6.6`

Terraform version (`terraform -v`): `Terraform v0.10.4`

### Terraform Configuration Files
```hcl
locals {
  abc = "123"
}

resource "dme_record" "my_dns_entry" {
  domainid = "${local.abc}"
  # etc
}
```

### Expected Behavior
Usage of `"${local.abc}"` has syntax highlighting, autocomplete, go-to-definition.

### Actual Behavior
Usage is flagged as error.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create `demo.tf`
2. Paste the above.
3. Place cursor over `"${local.abc}"` and observe error

**Comment by VladRassokhin** [comment]
Thank you for reporting, fixed that. Would be available in next plugin release which is planned to end of this week or next Monday, definitely before HashiConf starts :)

**Comment by johnsoft** [comment]
That was unbelievably fast, thanks!
