### ISSUE TITLE
Support for terraform_remote_state S3

### ISSUE THREAD

**Issue by darrenhaken** [VladRassokhin/intellij-hcl#108]
I am trying to reference Terraform remote state from an S3 bucket but whenever I reference it within my code I do not get auto complete and IntelliJ marks it as an error.

Example terraform remote state:

```
data "terraform_remote_state" "global" {
  backend = "s3"
  config {
    bucket = "bucket-name"
    key = "state.tfstate"
    region = "us-west-1"
  }
}
```

If I use other data backends like `aws_availability_zones` I do get auto complete.

Any help?

### Prerequisites
 - [X] Ensure you have latest version of plugin installed
 - [X] Search for possible issue duplicates

### IDE Version
RubyMine 2017.2.3
Build #RM-172.3968.40, built on September 1, 2017
Licensed to Auto Trader Limited / Darren Haken
You have a perpetual fallback license for this version
Subscription is active until July 31, 2018
JRE: 1.8.0_152-release-915-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5

[0.6.6 ] intellij-hcl plugin version (`Settings->Plugins`)
[0.10.4 ] Terraform version

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configuration here - for large Terraform configs,
# please use a gist (https://gist.github.com) and share a link. 
```

**Comment by VladRassokhin** [comment]
Well, technically it's nearly impossible to fetch some remote file from S3 and parse binary format (tfstate), so I'd like to avoid trying to implement that.
Though it's easier to just don't show errors in usages. Could you please attach some snippet which uses data from such remote backend?

**Comment by darrenhaken** [comment]
Sure so I have a remote storage file which is used for global AWS resources like IAM, storage etc.

I have a different Terraform state/stack which is then configuring an application and needs to reference params from global.

Example is:

```
resource "aws_launch_configuration" "launch_config" {
  name_prefix = "Some Launch Config"
  key_name = "${data.terraform_remote_state.global.ssh_key_name}"} <--- Here
```

**Comment by VladRassokhin** [comment]
Thank you for clarification.
It's impossible for now to implement autocompletion there, as there's no code in plugin which could read that state and won't be as far as it's complicated, maybe if Terraform would provide that data I'll add that.

At the same time 'unresolved reference' doesn't highlight that code as error since 'terraform_remote_state' specially marked to contain dynamic properties.

**Comment by darrenhaken** [comment]
It's a shame that Terraform doesn't expose this.

So what I've discovered is that if the property string contains full stops than the plugin will mark nested items as an error. This was a design choice to namespace the keys.

An example is:

![image](https://user-images.githubusercontent.com/953467/30518561-51c5d970-9b79-11e7-9a6d-4c59b1ac779e.png)

Would it be a lot of work to ensure dynamic properties will also accept `.` and not mark them as an error?

**Comment by VladRassokhin** [comment]
That's definitely is a bug, will look into.

**Comment by VladRassokhin** [comment]
Problem with unresolved references fixed in 352497a

**Comment by darrenhaken** [comment]
Awesome that was fast 👍 - when can we expect a release to IntelliJ with the update?

**Comment by darrenhaken** [comment]
I also see you are using Kotlin - nice :)

**Comment by VladRassokhin** [comment]
I'm going to release new update just before HashiConf kicks off, as I'll be there at JetBrains booth.

**Comment by darrenhaken** [comment]
Isn't Hashiconf today? 😃

**Comment by VladRassokhin** [comment]
Today but it's 6:24 am here, so I've plenty of time. First event would start at 5:30pm, keynote planned for tomorrow.

**Comment by darrenhaken** [comment]
Great OK so it sounds like within the next day or so which is awesome 👍 

Can you let me know when it's out?

**Comment by VladRassokhin** [comment]
Yep, I'll write comment here once it's out

**Comment by VladRassokhin** [comment]
I've released update yesterday with fix

**Comment by darrenhaken** [comment]
Thanks it all seems to be working 😄 - I appreciate you doing the work. I'll close this off.

**Comment by KaloyanP** [comment]
How do we get the TF peeps to give you what you need? Having autocomplete on remote state would be absolutely kickass!
