### ISSUE TITLE
Quote escapes does not pass validation

### ISSUE THREAD

**Issue by paykin** [VladRassokhin/intellij-hcl#111]
### Installation details
 - [x] IDE version ` 2017.2.5`
 - [x] intellij-hcl plugin version `0.6.7`
 - [x] Terraform version `Terraform v0.9.6`

### Terraform Configuration Files
```hcl
output "ecs_instance_public_ips_quote" {
  value = "${join(",", formatlist("\"%s\"", aws_instance.ecs_instance.*.public_ip))}"
}
```

### Expected Behavior
The mentioned output variable should be parsed properly without errors and the variable should be available in validations and autocomplete in the rest of the project

### Actual Behavior
There is validation error "Missing right quote" and this output and the rest of the file is not available in autocomplete and validation in other project files. The String is color-highlighted properly.

**Comment by jlsjonas** [comment]
Most likely the same issue: `missing closing quote`

for a more simpler: 
```tf
output "example" {
    value = "${join("\", \"",var.off_peak_periods)}"
}
```

**Comment by akrymets** [comment]
Having same issue. Following code:
`log_option_json  = "${var.log_driver == "json-file" ? "\"max-size\": \"2m\", \"max-file\": \"3\"" : "" }"
log_option_awslogs  = "${var.log_driver == "awslogs" ? "\"awslogs-group\": \"aaa\", \"awslogs-stream-prefix\": \"bbb\"" : ""}"`
leads to the "Missing closing quote" error, and the rest of the code is not parsed correctly.
