### ISSUE TITLE
Add new aws_lb resources

### ISSUE THREAD

**Issue by jkroepke** [VladRassokhin/intellij-hcl#116]
### Expected Behavior
All new aws_lb* resources should be known.

See https://github.com/terraform-providers/terraform-provider-aws/blob/v1.1.0/CHANGELOG.md for the new resources.

### Actual Behavior
All new aws_lb* resources are unknown

**Comment by VladRassokhin** [comment]
Fixed in 0.6.8 (already released two weeks ago)
