### ISSUE TITLE
How to use intellij-hcl plugin in Android Studio?

### ISSUE THREAD

**Issue by TinajaLabs** [VladRassokhin/intellij-hcl#117]
Sorry to be dense, but I have installed this plugin into Android Studio.  Now what?  

I found the plugin option and selected the intellij-hcl-0.6.7.zip file.  It seemed to install the plugin, because I now see it in the list of plugins and there is now an option to unInstall.  Also I see in the preferences > tools menu there is a Terraform option to enter the path to Terraform.

I have my existing setup already, but I can't see how to create a new terraform project.  I kind of expected to see something about open new Terraform Project.  All I get is an android project wizard.

It's probably obvious to most, but for the dense ones like me, please, some help.

The main thing I'm looking for is refactoring.  It is so necessary yet so painful in Sublime.

Thank you,
Chris.

**Comment by VladRassokhin** [comment]
Hi Chris,

Primary this plugins adds support for editing Terraform scripts, there's no functionality like creating any new type of projects. 
I'm not familiar with AndroidStudio, can't you just open directory as project as it could be done in IntelliJ IDEA?
If AS is not supporting that I could recommend to install IntelliJ IDEA Community Edition or PyCharm Community Edition, which are free and install plugin there.

Regards,
Vladislav

**Comment by TinajaLabs** [comment]
Thanks.  I think Android Studio is IntelliJ with android plugins.  I'll look at a virgin instance of IntelliJ IDEA Community Edition.  
Thanks,
Chris.
