### ISSUE TITLE
Updating "res/terraform/model"

### ISSUE THREAD

**Issue by Lavoaster** [VladRassokhin/intellij-hcl#118]
Hey There,

I was wondering how you went around updating the data in these folders. The definitions in this plugin are out of date, last synced `10.3` and we're on `10.8` now. 

I was looking on how you went around generating these, and submit a PR to update them, but I couldn't find out how.

Would you be able to document how you do it?

**Comment by VladRassokhin** [comment]
Hi,

I've [special fork of Terraform](https://github.com/VladRassokhin/terraform/tree/f-export-schema-master) to generate schemas for provisioners and functions. So the process is to rebase branch on top of latest release and run some [magic](https://github.com/VladRassokhin/utilities/blob/master/shell-scripts/export-terraform-schemas.sh).
And there's [special tool](https://github.com/VladRassokhin/intellij-hcl/tree/master/schemas-extractor) which extracts schemas for providers.

**Comment by Lavoaster** [comment]
Yep, I managed to come across your utility script, but got confused in trying to find out where the "schemas" command came from, the fork certainly explains it. :P

Thanks Vlad, I'll have a go at trying this next time they're out of date. (Seeing as you've just done it 😛 )

**Comment by VladRassokhin** [comment]
Yeah, I'll try to write some proper documentation/script for that process.
