### ISSUE TITLE
"route" flagged as unknown block inside "aws_route_table" resource

### ISSUE THREAD

**Issue by SpencerBrown** [VladRassokhin/intellij-hcl#12]
latest plugin 0.4.1

```
resource "aws_route_table" "something"
{
  vpc_id = "vpc-something"
  route {
    cidr_block = "0.0.0.0/0"
    instance_id = "id-something"
  }
}
```
the `route` line gets yellow flagged by inspector
`unknown block type route`

**Comment by SpencerBrown** [comment]
Similarly, I am seeing the `tags` block flagged within an `as_instance` resource

**Comment by VladRassokhin** [comment]
Will release new plugin a bit later (on weekend, probably), as workaround you could disable inspection.

**Comment by VladRassokhin** [comment]
@SpencerBrown Published new plugin version (0.4.2). Try it please.

**Comment by SpencerBrown** [comment]
Just got prompted to install new plugin. Works like a champ. All my `.tf` files are now proudly showing green checkmarks. And the previously missing blocks are now showing as options when I hit ctrl+space.

Thanks!!

**Comment by VladRassokhin** [comment]
@SpencerBrown  Glad to hear that,
If you have ideas what to improve in plugin feel free to share them here, by email, or create new issues.
