### ISSUE TITLE
WARN - eInsight.daemon.LineMarkerInfo

### ISSUE THREAD

**Issue by dlsniper** [VladRassokhin/intellij-hcl#124]
### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`)
GoLand 2017.3 EAP
Build #GO-173.3727.93, built on November 23, 2017
GoLand EAP User
Expiration date: December 23, 2017
JRE: 1.8.0_152-release-1024-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-17-generic
 - [x] intellij-hcl plugin version (`Settings->Plugins`)
HashiCorp Terraform / HCL language support (0.6.9.1)
 - [x] Terraform version (`terraform -v`)
Terraform v0.11.0

### Terraform Configuration Files
n/a

### Exception
```text
2017-11-23 18:41:56,117 [7772553]   WARN - eInsight.daemon.LineMarkerInfo - Performance warning: LineMarker is supposed to be registered for leaf elements only, but got: HCLBlock (class org.intellij.plugins.hcl.psi.impl.HCLBlockImpl) instead. First child: HCLIdentifier (class org.intellij.plugins.hcl.psi.impl.HCLIdentifierImpl)
Please see LineMarkerProvider#getLineMarkerInfo(PsiElement) javadoc for detailed explanations. 
```

### Expected Behavior
Not see that in the log file

### Actual Behavior
That was in the log file

### Steps to Reproduce
Use the plugin in GoLand.
Open a project without any terraform file in it.
Add a content root for a project that does contain terraform files in it.

**Comment by VladRassokhin** [comment]
Investigation showed that such LineMarkers provided by `com.intellij.execution.lineMarker.RunLineMarkerProvider` which gets elements from `TerraformRunLineMarkerContributor` which obviously registers gutter 'run' actions for 'resource' blocks.

**Comment by VladRassokhin** [comment]
@dlsniper thank you for reporting problem

**Comment by dlsniper** [comment]
Thank you for fixing it so quickly. It's an awesome plugin, thank you for all the work on it.
