### ISSUE TITLE
Updating PHPStorm to 2017.3 shows a warning

### ISSUE THREAD

**Issue by xgathos** [VladRassokhin/intellij-hcl#125]
Hi

PhpStorm 2017.2.4 with 0.6.9.2 installed warns while updating to 2017.3: "Plugin incompatible with the new build found: HashiCorp Terraform / HCL Language support"

best
André

**Comment by ttyS0** [comment]
Same for IntelliJ. I'm holding off on updating for now.

**Comment by VladRassokhin** [comment]
Actually version is compatible, there's just 'until' build was set up in plugin xml to not force plugin update where it was unnecessary. 
For now you can remove plugin, update IDE and install plugin again.

**Comment by ttyS0** [comment]
Yep, that worked. :) Thanks!

**Comment by VladRassokhin** [comment]
Just uploaded version 0.6.9.3, it should work for all latest IDEs

**Comment by xgathos** [comment]
it's working :)  thank you!

**Comment by ketzacoatl** [comment]
That worked for me on a new install of the latest release of PyCharm, thank you @VladRassokhin!
