### ISSUE TITLE
Plugin incompatibility warning for IDEA 2017.3

### ISSUE THREAD

**Issue by trung** [VladRassokhin/intellij-hcl#127]
I didn't go ahead to upgrade my IDEA and tried to see if the plugin still works. 

If it still works, this is the false alarm.

![image](https://user-images.githubusercontent.com/24930/33576044-9b1b6f6a-d90c-11e7-85ee-9a141dbac67b.png)

**Comment by VladRassokhin** [comment]
Duplicate of #125
