### ISSUE TITLE
Document support for custom providers 

### ISSUE THREAD

**Issue by gberche-orange** [VladRassokhin/intellij-hcl#128]
Thanks for contributing this great plugin! When trying autocompletion, I only see the standard provider resources listed, and their properties. I'd like to have completion on custom providers (e.g. https://github.com/orange-cloudfoundry/terraform-provider-cloudfoundry or https://github.com/mevansam/terraform-provider-cf)

It seems that plugin embeds json models for default plugins, and that additional custom providers can be supported by providing their json model into  ~/.terraform.d/schemas/*.json files on Linux/OSX and %APPDATA%/terraform.d/schemas/*.json on Windows according to https://github.com/VladRassokhin/intellij-hcl/issues/75#issuecomment-285735365

Searching around for ways to generate the json model for custom providers, I ran into `schemas-extractor` dir in this repo which seems used to generate schemas for official providers. 

I'm starting tweaking it to generate json model for custom providers.  Is there a better way ? If not, might make sense to have a build-and-install-custom.sh script that would take a git repo url (or a path to a local clone) and would generate the model and copy it into ~/.terraform.d/schemas/*.json 

### Installation details
 - [ ] IDE version (`Help->About->Copy to Clipboard`) 2017.2.6 (buiold IU-172-457-11)
 - [ ] intellij-hcl plugin version (`Settings->Plugins`) : 0.6.9.3
 - [ ] Terraform version (`terraform -v`) 0.11.1

**Comment by gberche-orange** [comment]
I tried the tweak into https://github.com/gberche-orange/intellij-hcl/commit/f7064f68fe0959053c95e55f7f7a2af7c2cabbe4  
It seems that the expectation is the provider repo contains a package named after the provider name.

The modified script invoked with

```
export GOPATH=/home/guillaume/go; ./build-and-install-custom.sh terraform-provider-cf https://github.com/mevansam/terraform-provider-cf.git
```

with the provider previously cloned using 

```
$ mkdir -p $GOPATH/src/github.com/terraform-providers; cd $GOPATH/src/github.com/terraform-providers
$ git clone git@github.com:terraform-providers/terraform-provider-cf
```

initial failed with message:

```
generate-schema/generate-schema.go:6:2: cannot find package "github.com/terraform-providers/terraform-provider-cf/cf" in any of:
        /home/guillaume/go/src/github.com/terraform-providers/terraform-provider-cf/vendor/github.com/terraform-providers/terraform-provider-cf/cf (vendor tree)
        /usr/local/go1.9/src/github.com/terraform-providers/terraform-provider-cf/cf (from $GOROOT)
        /home/guillaume/go/src/github.com/terraform-providers/terraform-provider-cf/cf (from $GOPATH)
```

I ended up tweaking the generated ``generate-schema.go`` file to reference the proper cloudfoundry package 

Here is the modified template and the resulting json model:
https://github.com/mevansam/terraform-provider-cf/compare/master...gberche-orange:intellij-hcl?expand=1

**Comment by ArthurHlt** [comment]
Here a customized version of the generator for a community provider:
https://gist.github.com/ArthurHlt/45d4207c557dd614735a4aabc3d12976

**Comment by matthew16550** [comment]
In future there might be a Terraform cli command to do this, see hashicorp/terraform#17018.

**Comment by VladRassokhin** [comment]
In 0.6.14 I've introduced support for loading model from external repo. Documented in ReadMe.
There's also [external repo](https://github.com/VladRassokhin/terraform-metadata) with metadata. Will document update process there.

**Comment by gberche-orange** [comment]
Since the repo has been handed to jetbrains, this enhancement request can be tracked at https://youtrack.jetbrains.com/issue/IDEA-240192 although [ReadMe.md#deprecation-notice](https://github.com/VladRassokhin/intellij-hcl/blob/master/ReadMe.md#deprecation-notice) mentions:

> Though this repository is still used as issue tracker, so please create new issues here rather than in JetBrains tracker since plugin releases separately and it's simpler to track issues here.
