### ISSUE TITLE
Align `=` on `Reformat Code`

### ISSUE THREAD

**Issue by willfarrell** [VladRassokhin/intellij-hcl#129]
Not sure if this belongs here or not.

### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
IntelliJ IDEA 2017.3 (Ultimate Edition)
Build #IU-173.3727.127, built on November 27, 2017
Licensed to William Farrell
Subscription is active until October 15, 2018
JRE: 1.8.0_152-release-1024-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.1

Plugin Version: 0.6.9.3

Terraform v0.11.1

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configuration here - for large Terraform configs,
# please use a gist (https://gist.github.com) and share a link. 
```

### Source
Too many spaces at the beginning, `=` not aligned
```hcl
variable "aws_region" {
    type   = "string"
    default = "ca-central-1"
}
```
### Expected Behavior
2 space tabs, aligned `=`
```hcl
variable "aws_region" {
  type     = "string"
  default = "ca-central-1"
}
```
### Actual Behavior
2 spaced tabs, `=` not aligned
```hcl
variable "aws_region" {
  type = "string"
  default = "ca-central-1"
}
```
### Steps to Reproduce
Press `option` + `command` + `L`

**Comment by VladRassokhin** [comment]
You can configure formatting options in `Settings -> Code Style -> Terraform Configuration Files`
There're options for tabbing and aligning.

**Comment by willfarrell** [comment]
Found a way: Run `tf fmt` in the root of the project. Does it all.

**Comment by VladRassokhin** [comment]
@willfarrell also you can configure file watcher to automatically run `terraform fmt` on file save.
