### ISSUE TITLE
Exception in latest PyCharm

### ISSUE THREAD

**Issue by jweede** [VladRassokhin/intellij-hcl#13]
I've been using this excellent plugin in PyCharm. Since the 4.5.4 update I've started seeing the following error:

    NoClassDefFoundError: com/intellij/psi/impl/source/tree/injected/StringLiteralEscaper

Any thoughts?

**Comment by VladRassokhin** [comment]
Looks like this class present only in IntelliJ IDEA, will use another class in hext plugin version

**Comment by jweede** [comment]
Thanks for the quick response. Looking forward to it.

**Comment by VladRassokhin** [comment]
Published new plugin version (0.4.2). Try it please.

**Comment by jweede** [comment]
Fixes the issue. Thanks again!
