### ISSUE TITLE
How do you update the autocomplete for providers

### ISSUE THREAD

**Issue by darrenhaken** [VladRassokhin/intellij-hcl#131]
The AWS 1.7.0 provider has been released and I cannot see auto-completion as a new resource.
What is the process to update the auto-completion on provider changes?

I'm happy to contribute to the codebase to update it if you tell me how 😄

**Comment by synesisinc** [comment]
Same question here... any updates on this?

**Comment by VladRassokhin** [comment]
Right now it's kind of manual process. Explained in https://github.com/VladRassokhin/intellij-hcl/issues/118#issuecomment-341231163
Will try to update plugin this week

**Comment by darrenhaken** [comment]
Need any help getting it automated?

**Comment by VladRassokhin** [comment]
Would be nice. Also someone else in #128 doing something similar, haven't had time to look into yet.

**Comment by robh007** [comment]
Hi, @VladRassokhin 

I tried to update the providers & associated resources for autocompletion. So I ran the make file which generated all schema's successfully. The new AWS resources I'm interested in are visible in the json file. I ran a ./gradlew build which generated a new zip file. I even changed the version just in case intellij did something weird. I installed the plugin restarted intellij and those resources don't appear. What am I missing? This is a great plugin so I appreciate all the effort, maybe a weekly new build could be triggered, given the AWS provider is pretty much released weekly.

**Comment by robh007** [comment]
Ok - I've worked out what was wrong. The make process for the provider resources just creates JSON files and the gradle build takes files from the res/ directory. So the make process for provider updates doesn't appear to copy the newly outputted JSON files into the correct place.

**Comment by VladRassokhin** [comment]
@robh007 Yep, files have to be moved, though there's manual process of updating some of them like providers.list.
I have an idea how to update them automatically, though it's not final yet and not implemented yet :(

**Comment by VladRassokhin** [comment]
In 0.6.14 I've introduced support for loading model from external repo. Documented in ReadMe.
