### ISSUE TITLE
Format with same indents

### ISSUE THREAD

**Issue by jonnyzzz** [VladRassokhin/intellij-hcl#133]
I have the code, eg.g
```
resource "aws_ecr_repository_policy" "" {
  policy = ""
  repository = ""
}
```

I want it to be formatted as 

```
resource "aws_ecr_repository_policy" "" {
  policy       = ""
  repository = ""
}
```
The plugin tends to format as shown above, which reads harder (to me)

**Comment by VladRassokhin** [comment]
Take a look on code style settings, there's dropdown there for alignment. Though terraform-style alignment is not supported as it requires splitting properties onto 'blocks' based on EOL statements.

**Comment by VladRassokhin** [comment]
![intellij-hcl code style alignment](https://user-images.githubusercontent.com/552079/35216227-f4662c0e-ff77-11e7-84c0-46d3378cc873.png)
