### ISSUE TITLE
Navigate to documentation

### ISSUE THREAD

**Issue by jonnyzzz** [VladRassokhin/intellij-hcl#134]
Let's make plugin help me by navigating to documentation pages. 

For example if I see 
```
resource "aws_ecr_repository_policy" "" {
  policy = ""
  repository = ""
}
```

I'd like to be navigated with my default browser to the documentation page so I was able to realize what exactly it mean and how one uses the paramerer

**Comment by VladRassokhin** [comment]
Duplicates #113

**Comment by jonnyzzz** [comment]
It worked. Thanks!

The only potential problem 
```
<component name="ProjectCodeStyleConfiguration">
  <code_scheme name="Project" version="173">
    <HCL-Terraform>
      <option name="PROPERTY_ALIGNMENT" value="2" />
    </HCL-Terraform>
  </code_scheme>
</component>
```

Magic value `2` can be too easy to break in the future, probably

**Comment by eschwartz** [comment]
> It worked. Thanks!

@jonnyzzz -- were you able to get external documentation working somehow?

**Comment by VladRassokhin** [comment]
@eschwartz I bet @jonnyzzz's comment is about another issue and he just missed tab with proper one.
