### ISSUE TITLE
Spurious "Missing required properties" for intentionally unconfigured providers

### ISSUE THREAD

**Issue by eriksw** [VladRassokhin/intellij-hcl#138]
The "Missing required properties" inspection raises spurious warnings when working with terraform modules that receive providers.

When you need to pass a specific instance of a provider from a workspace or parent module to a module, the module that needs to receive and use a specific provider must have an unconfigured/stub provider. 

Example `myenv/main.tf`:

```hcl
provider "aws" {
  region = "us-west-2"
  profile = "default"
  version = "= 1.8.0"
}

provider "aws" {
  alias = "backups-east"
  region = "us-east-1"
  profile = "backups"
  version = "= 1.8.0"
}

module "backups" {
  source = "../modules/backup-bucket"
  name = "foobar"

  providers = {
    aws = "backups-east"
  }
}
```

Example `modules/backup-bucket/main.tf`:

```hcl
provider "aws" { }

variable "name" {
  type = "string"
}

resource "aws_s3_bucket" "backup" {
  bucket = "${var.name}"
}
```

In this example, while editing `modules/backup-bucket/main.tf`, there is a spurious warning about `Missing required properties: region` re `provider "aws" { }`, when it is in fact required that the provider configuration *not* be populated in this situation. For more info, see: https://github.com/hashicorp/terraform/blob/master/website/docs/modules/usage.html.markdown#providers-within-modules

I'm seeing this with plugin version `0.6.9.4` on `IntelliJ IDEA 2018.1 EAP (Ultimate Edition)
Build #IU-181.3007.14, built on January 24, 2018`.

**Comment by VladRassokhin** [comment]
In 0.6.10 it would be possible to suppress inspections for some blocks/properties using `//noinspection X` comments, e.g. 
```hcl
//noinspection MissingProperty
provider "aws" {
}
```
