### ISSUE TITLE
Plugin is not showing up in Rider

### ISSUE THREAD

**Issue by mboudreau** [VladRassokhin/intellij-hcl#140]
Was trying to install Terraform plugin with my version of Rider (latest one) and the plugin never shows in my plugins list, like if it's getting filtered out somehow.

### Prerequisites
 - [n/a] Ensure you have latest version of plugin installed
 - [✓] Search for possible issue duplicates

### Installation details
 - [JetBrains Rider 2017.2.1 Build #RD-172.4144.1873 ] IDE version (`Help->About->Copy to Clipboard`)
 - [n/a] intellij-hcl plugin version (`Settings->Plugins`)
 - [0.11.1] Terraform version (`terraform -v`)

### Terraform Configuration Files
n/a

### Exception
none

### Expected Behavior
Plugins shows up in plugins list

### Actual Behavior
Nothing shows under 'terraform' or 'hcl'

### Steps to Reproduce
File -> Settings -> Plugins -> Install Jetbrains Plugin -> input 'hcl' in search box -> nothing

**Comment by VladRassokhin** [comment]
Hm, I've just tried on Rider 2017.3.1 and plugin installed and showed correctly in plugins list after Rider restart.

**Comment by mboudreau** [comment]
I mean, before install, as in, in trying to install it and it's not coming
up in the available plugins list. Works in intellij and webstorm, but not
rider.

**Comment by VladRassokhin** [comment]
Well, both in Rider 2018.1 and 2018.2 there's no issues with plugin appearing in list even when it's not installed. Probably there was some error in Rider or plugins repo at that time
