### ISSUE TITLE
Unknown block type timeouts

### ISSUE THREAD

**Issue by blckct** [VladRassokhin/intellij-hcl#145]
### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`) PhpStorm 2017.3.4
 - [x] intellij-hcl plugin version (`Settings->Plugins`) 0.6.9.5
 - [x] Terraform version (`terraform -v`) v0.11.5

### Terraform Configuration Files
The example from Terraform page:
```hcl
resource "aws_db_instance" "timeout_example" {
  allocated_storage = 10
  engine            = "mysql"
  engine_version    = "5.6.17"
  instance_class    = "db.t1.micro"
  name              = "mydb"

  # ...

  timeouts {
    create = "60m"
    delete = "2h"
  }
}
```

### Expected Behavior
What should have happened?

### Actual Behavior
Some AWS resource in Terraform support the timeouts block, however the plugin marks it as warning saying it's unknown. https://www.terraform.io/docs/configuration/resources.html#timeouts

### Steps to Reproduce
1. Try to add timeouts block to any resource that supports it, i.e. aws_instance.

I would've made a PR against https://github.com/VladRassokhin/intellij-hcl/blob/master/res/terraform/model/providers/aws.json but I'm not sure if that file is hand-crafted or generated.

**Comment by VladRassokhin** [comment]
> I would've made a PR against https://github.com/VladRassokhin/intellij-hcl/blob/master/res/terraform/model/providers/aws.json but I'm not sure if that file is hand-crafted or generated.

It's generated, I'd update it before next release which is due this week.
Thanks for reporting.

**Comment by blckct** [comment]
Thanks.
