### ISSUE TITLE
Add support for google_compute_vpn_gateway creation_timestamp reference

### ISSUE THREAD

**Issue by kickin6** [VladRassokhin/intellij-hcl#149]
Reference: https://www.terraform.io/docs/providers/google/r/compute_vpn_gateway.html#attributes-reference

### Prerequisites
 - [X] Ensure you have latest version of plugin installed
 - [X] Search for possible issue duplicates

### Installation details
 - [X] IDE version (`Help->About->Copy to Clipboard`)
IntelliJ IDEA 2018.1.3 (Ultimate Edition)
Build #IU-181.4892.42, built on May 7, 2018
JRE: 1.8.0_152-release-1136-b38 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4

 - [X] intellij-hcl plugin version (`Settings->Plugins`)
0.6.10

 - [X] Terraform version (`terraform -v`)
v0.11.7

### Terraform Configuration Files
```hcl
resource "google_compute_vpn_gateway" "main" {
  name    = "myvpn"
  region  = "us-east4"
  network = "network-self_link-here"
}

output "vpn_gateway_creation_timestamp" {
  value = "${google_compute_vpn_gateway.main.creation_timestamp}"
}
```

### Exception
None

### Expected Behavior
What should have happened?

In IntelliJ, `creation_timestamp` in `google_compute_vpn_gateway.main.creation_timestamp` text should be white indicating a valid reference.

### Actual Behavior
What actually happened?

In IntelliJ, `creation_timestamp` text is red indicating an unresolved reference. 

`terraform plan` and `terraform apply` ran without error.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a network and get or reference the self_link.
2. Create a gateway resource and output.
3. Verify in IntelliJ that text is red and an `Unresolved reference creation_timestamp` error is indicated

**Comment by VladRassokhin** [comment]
Fixed in 0.6.11 (released a month ago)
