### ISSUE TITLE
Syntax update for templates in Terraform 0.6.7

### ISSUE THREAD

**Issue by xsmaster** [VladRassokhin/intellij-hcl#15]
When using the plug in with rubymine I get an warning about not having the "filename".  They just made this change so just wanted you to know about it. 

[Template Providers](https://www.terraform.io/docs/providers/template/r/file.html)
> filename - _Deprecated, please use template instead. The filename for the template. Use path variables to make this path relative to different path roots.

```
resource "template_file" "init" {
    filename = "${file("${path.module}/init.tpl")}"

    vars {
        consul_address = "${aws_instance.consul.private_ip}"
    }
}
```

vs

```
resource "template_file" "init" {
    template = "${file("${path.module}/init.tpl")}"

    vars {
        consul_address = "${aws_instance.consul.private_ip}"
    }
}
```

**Comment by VladRassokhin** [comment]
Model updated from Terraform 0.6.8 in plugin 0.4.3. Hopefully this issue fixed.
