### ISSUE TITLE
Terraform Interpolation Syntax Highlighted as Syntax Error in Pycharm

### ISSUE THREAD

**Issue by taruntmr** [VladRassokhin/intellij-hcl#152]
### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`)
PyCharm 2018.1.4 (Professional Edition)
Build #PY-181.5087.37, built on May 24, 2018
Licensed to Tarun Tomar
Subscription is active until July 6, 2018
JRE: 1.8.0_152-release-1136-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.5

 - [x] intellij-hcl plugin version (`Settings->Plugins`)
0.6.11
 - [x] Terraform version (`terraform -v`)
0.11.7
### Terraform Configuration Files
```hcl
key_name = "${format("%s-Bastion-%s", var.ProjectName, var.RegionName)}" 
```

### Exception
```text
Should not highlight any errors.
```

### Expected Behavior
PyCharm should not highlight any error

### Actual Behavior
Throws syntax error. Making the remaining code styling/highlights fail.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. use the terraform interpolation to format a a variable value using couple of other variables, such as:

var1 = "abc"
var2 = "${format("%s", var.var1)}"

Upon hovering the mouse to the highlighted syntax error, it reads:
```
',' or '}' expected, got '%'
```

**Comment by VladRassokhin** [comment]
Unfortunately I cannot reproduce with code snippet you provided. Could you please send me full config or attach screenshot showing this problem here.

**Comment by taruntmr** [comment]
Hi,

Below are couple of screenshots w.r.t this issue:

<img width="250" alt="screen shot 2018-07-04 at 11 23 14 am" src="https://user-images.githubusercontent.com/20217062/42259152-e4ae48ac-7f7c-11e8-9e93-806d2fba7de4.png">
<img width="296" alt="screen shot 2018-07-04 at 11 23 04 am" src="https://user-images.githubusercontent.com/20217062/42259153-e4e4af32-7f7c-11e8-89f9-3824ac649813.png">
<img width="772" alt="screen shot 2018-07-04 at 11 20 12 am" src="https://user-images.githubusercontent.com/20217062/42259154-e51c3b28-7f7c-11e8-99f6-5c4fbaea9979.png">
<img width="790" alt="screen shot 2018-07-04 at 11 19 55 am" src="https://user-images.githubusercontent.com/20217062/42259155-e550848c-7f7c-11e8-84f3-2432fee40315.png">

**Comment by VladRassokhin** [comment]
Thanks, screenshot helps. In original issue there was no mention about multiline nature of value.

**Comment by VladRassokhin** [comment]
Last question: please check that file extension is  'tf' and PyCharm detect it as 'Terraform Config' language

**Comment by taruntmr** [comment]
Hi,

The config seems to be good above the line, below screen shot for reference. Also, in the screen shot you would see that the file is a .tf extension.
<img width="988" alt="screen shot 2018-07-04 at 6 43 19 pm" src="https://user-images.githubusercontent.com/20217062/42279139-73768256-7fba-11e8-91b4-44a9302a118a.png">

I am not certain on the "PyCharm detect it as 'Terraform Config' language".

**Comment by taruntmr** [comment]
Here is another screenshot of a different file (same name: main.tf). Here the error presents itself in the tags line (single line value).

<img width="901" alt="screen shot 2018-07-04 at 6 46 40 pm" src="https://user-images.githubusercontent.com/20217062/42279235-c6de3790-7fba-11e8-9ffb-d257b985e833.png">

When I change the language reference to HCL then multiple error get highlighted as you may see in the below screen shot.

<img width="1258" alt="screen shot 2018-07-04 at 6 48 28 pm" src="https://user-images.githubusercontent.com/20217062/42279313-02f3498c-7fbb-11e8-96e3-be2301c0f4a7.png">

**Comment by taruntmr** [comment]
Hi,

Thanks for all your responses and time and effort for this awesome plugin.

I had associated the *.tf with HCL Interpolation Language and hence the syntax issue.

All seems to be working fine now.

**Comment by VladRassokhin** [comment]
Ok. If you spot some problems don't hesitate to open new issues.
