### ISSUE TITLE
Formatter breaks HEREDOC in array

### ISSUE THREAD

**Issue by GabrielCastro** [VladRassokhin/intellij-hcl#153]
Thank you for opening an issue.
In this template paragraph text could be removed, however please retain headers.

### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`)
```
IntelliJ IDEA 2018.1.5 (Ultimate Edition)
Build #IU-181.5281.24, built on June 12, 2018
Licensed to Gabriel Castro
Subscription is active until October 22, 2018
For educational use only.
JRE: 1.8.0_152-release-1136-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.5
```
 - [x] intellij-hcl plugin version (`Settings->Plugins`)
``` 0.6.11```
 - [x] Terraform version (`terraform -v`)
```
Terraform v0.11.7
+ provider.aws v1.23.0
+ provider.external v1.0.0
+ provider.helm (unversioned)
+ provider.kubernetes v1.1.0
```

### Terraform Configuration Files
```hcl
locals {
  a_local = [
    <<DATA
This is some data string
DATA
,
    "some other data",
  ]
}
```

### Expected Behavior
When I use the format action it should produce valid HCL with out breaking heredoc like
```hcl
locals {
  a_local = [
    <<DATA
This is some data string
DATA
    ,
    "some other data",
  ]
}
```

### Actual Behavior
The comma is placed with the ending heredoc marker making it invalid

```hcl
locals {
  a_local = [
    <<DATA
This is some data string
DATA,
    "some other data",
  ]
}
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. place the code from the expected section in a .tf file
2. use the format action (⌘-⌥-L)

**Comment by VladRassokhin** [comment]
Thank you for reporting, would be fixed in upcoming release
