### ISSUE TITLE
Show a variable description and default value

### ISSUE THREAD

**Issue by sugdyzhekov** [VladRassokhin/intellij-hcl#154]
It would be nice and useful to see variable description and a default value if they exist.

```
variable "desired_capacity" {
  description = "The maximum size of the auto scale group."
  default = "3"
}
```

**Comment by haidaraM** [comment]
That will be a nice feature to have on hover for instance...

**Comment by VladRassokhin** [comment]
Actually `Quick Documentation (Cmd+Q)` shows it since Sep 2017.
![intellij-hcl variable quick documentation](https://user-images.githubusercontent.com/552079/60888336-3669b180-a25f-11e9-8e6e-942a6d47c77b.png)

**Comment by haidaraM** [comment]
Cool, I haven't noticed that before.

**Comment by VladRassokhin** [comment]
Added default value to documentation, will be available in next plugin release.
