### ISSUE TITLE
Support HCL2 and Terraform 0.12

### ISSUE THREAD

**Issue by mkuzmin** [VladRassokhin/intellij-hcl#155]
A preview of Terraform 0.12 and HCL2 with a bunch of new features and breaking compatibility changes have been [announced](https://www.hashicorp.com/blog/terraform-0-1-2-preview).
They are planning to release it *later this summer*.

Our plugin needs to support it at some point.

**Comment by StephenKing** [comment]
seems like it's time to get started ;-)
https://github.com/hashicorp/terraform/releases/tag/v0.12.0-alpha1

**Comment by giladsh1** [comment]
We use this plugin on a daily basis.
would be awesome if it will support the new HCL2 format!

**Comment by cehrig** [comment]
+1, I don't like "First-Class Expressions" being marked as mistake

**Comment by tskotov** [comment]
+1 for HCL2/TF0.12 support!

**Comment by VladRassokhin** [comment]
>"First-Class Expressions" being marked as mistake

@cehrig what do you mean?

**Comment by cehrig** [comment]
@VladRassokhin 

I'm referring to this:

![2018-12-17_22-54](https://user-images.githubusercontent.com/13738610/50118067-da055d00-024e-11e9-82b8-db48b00ed894.png)

https://www.hashicorp.com/blog/terraform-0-12-preview-first-class-expressions

**Comment by mkuzmin** [comment]
check out https://www.youtube.com/watch?v=ZgXFlTZZaIg&list=PL4z1WbdlT5GKw1l2w0U-8YijoTwZp_GvU&index=5

event if Terraform provides a migration tool, I'm sure we have plenty of places for useful inspections

**Comment by d-helios** [comment]
Terraform 0.12-beta1 now available! It will be nice to see HCL2 support in favourite IDE ))

**Comment by StephenKing** [comment]
@VladRassokhin we're heavy users of this great plugin and looking forward to Terraform 0.12.

Is there any way how we can help to sponsor development?

**Comment by suslovsergey** [comment]
if i can donate for resolving this issue - i will donate!

**Comment by VladRassokhin** [comment]
HCL2 (Terraform 0.12+) support will be part of IntelliJ-Terraform plugin for IntelliJ 2019.2 as plugin will become part of IntelliJ.

You can kinda-sponsor development - buy any JetBrains product.

**Comment by brikis98** [comment]
Looking forward to seeing this! 

Is 0.12 support part of the [2019.2 EAP](https://confluence.jetbrains.com/display/IDEADEV/IDEA+2019.2+EAP)?

**Comment by Tom-Mann** [comment]
Don't see this in the 2019.2 intellij/pycharm releases ?

**Comment by bohdanyurov-gl** [comment]
TF 0.12 has been released: https://www.hashicorp.com/blog/announcing-terraform-0-12

**Comment by bohdanyurov-gl** [comment]
@VladRassokhin is there any estimated release date or an issue tracker?

**Comment by Acen** [comment]
> @VladRassokhin is there any estimated release date or an issue tracker?

There aren't any references within their bug tracker. https://youtrack.jetbrains.com/issues

**Comment by ajorpheus** [comment]
It appears there is an hcl2 branch for this plugin so @VladRassokhin has/had started working on it: https://github.com/VladRassokhin/intellij-hcl/tree/hcl2  but it was last updated in Aug, 2018 so a not sure what state it's in.

**Comment by VladRassokhin** [comment]
As I've stated a bit early
>HCL2 (Terraform 0.12+) support will be part of IntelliJ-Terraform plugin for IntelliJ 2019.2

Unfortunately not yet in 2019.2 EAP 1, though I'll investigate whether it's possible to publish plugin on plugins.jetbrains.com (build compatible with 2019.2 EAP or 2019.1.2)

All necessary code for HCL2 is already there, however it's not open-source

**Comment by ajorpheus** [comment]
> though I'll investigate whether it's possible to publish plugin on plugins.jetbrains.com (build compatible with 2019.2 EAP or 2019.1.2)

This will be awesome.

Unfortunately (or fortunately), I've found the Terraform integration in Intellij to be much better than VS Code and that's pretty much due to how well this plugin works.

**Comment by bowczarek** [comment]
As some guys told that already above, TF/HCL support in IJ awesome, thanks a lot! 
Me and my teammates also are waiting for TF0.12/HCL 2.0 support since we already migrated our code base because of so many great features and finally expressions treated as first class citizens.

Having that said @VladRassokhin do you have any sort of ETA when a new plugin may come up, either for 2019.1.2 or 2019.2 EAP as you mentioned already?

**Comment by OGProgrammer** [comment]
![Please fix it Vlad! JetBrains should pay this man.](https://aws1.discourse-cdn.com/pocketgems/uploads/wardragons/original/3X/8/e/8eadf29a49d87350915d5211084cf2569e6c30eb.jpeg)

**Comment by VladRassokhin** [comment]
I've uploaded version 0.7.0 to plugins repository.
It's compatible with IntelliJ platform 2019.1+, please try it out.

Possible caveats: new templates syntax (`%{}`).
Please report bugs if any.

**Comment by bohdanyurov-gl** [comment]
@VladRassokhin looks like TF 0.12 is supported only partially, code navigation or inspections do not work.

Anyway, thank you for uploading it,  at least it does not try to mark every template as broken now :)

**Comment by VladRassokhin** [comment]
@bohdanyurov-gl Examples maybe? It's hard to see what you mean since I'm not developing Terraform  configs daily.

**Comment by benosman** [comment]
@VladRassokhin 

Thanks for your work on this plugin.

A couple of things I noticed that don't yet work:

* Variables can now have more types, such as bool, number and also more complex type constructors:
Docs -> https://www.terraform.io/docs/configuration/variables.html#type-constraints
Example -> https://pasteboard.co/Ih9t0a1.png

* Complex lookups inside templates show as unresolved references. The new template system allows for some very dynamic code which is likely impossible for the plugin to determine, very often though they are highlighted red due to being unresolved. 
Example -> https://pasteboard.co/Ih9vCjB.png

**Comment by bohdanyurov-gl** [comment]
@VladRassokhin 
Even trivial constructions don't work:
![image](https://user-images.githubusercontent.com/47155283/58915944-eb71f100-872a-11e9-93a2-3e377fe4558e.png)

IDEA does not see "locals.foo" as a reference to the local variable.

Example for tf 0.11 syntax:
![image](https://user-images.githubusercontent.com/47155283/58915970-02184800-872b-11e9-99e7-0d9072c352df.png)

**Comment by bohdanyurov-gl** [comment]
Update: sorry for confusion. Looks like I was using v0.7.1, latest one works

**Comment by VladRassokhin** [comment]
Please open new issues if problems arises
