### ISSUE TITLE
Heredoc breaks formatting (<<EOF...EOF)

### ISSUE THREAD

**Issue by j0hnsmith** [VladRassokhin/intellij-hcl#164]
### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`)
GoLand 2018.2.2
Build #GO-182.4129.57, built on August 23, 2018
Licensed to someone
Subscription is active until May 21, 2019
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.12.6

 - [x] intellij-hcl plugin version (`Settings->Plugins`)
0.6.12
 - [x] Terraform version (`terraform -v`)
v0.11.7

### Terraform Configuration Files
```hcl
resource "aws_s3_bucket" "somesite" {
  region = "${local.region}"
  bucket = "somesite-com"
  acl    = "public-read"
  website {
    index_document = "index.html"
    //    error_document = "error.html"
  }
  policy = <<POLICY
{
  "Version":"2012-10-17",
  "Statement":[{
	"Sid":"PublicReadGetObject",
      "Effect":"Allow",
	  "Principal": "*",
      "Action":["s3:GetObject"],
      "Resource":["arn:aws:s3:::somesite-com/*"]
    }
  ]
}POLICY

}

output "somesite_website_endpoint" {
  value = "${aws_s3_bucket.somesite.website_endpoint}"
}
```

### Expected Behavior
What should have happened?

The `output` block at the bottom of the config should be formatted correctly. If I move it about the `resource` block (eg before the heredoc block) it is formatted correctly.

### Actual Behavior
What actually happened?

![screenshot](https://www.dropbox.com/s/rn4yz0ad36po7nt/p6ee511w.png?raw=1)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

Create config with a `<<EOF...EOF` block that also has additional config after it, the config after won't be formatted correctly.

Interesting that the github code formatting has the same formatting problem.

**Comment by VladRassokhin** [comment]
I think the problem here is that second `POLICY` should start on newline, not after some characters. Even highlighting shows that

**Comment by j0hnsmith** [comment]
Ahh, thanks, that works. 

However it seems to be valid syntax without the new line, as far as terraform is concerned (it runs it without complaining), and `terraform fmt` doesn't correct it. Happy to close though.

**Comment by VladRassokhin** [comment]
That was actually a bug in hcl parser itself, resolved in https://github.com/hashicorp/hcl/pull/245
AFAIU future versions of Terraform would not support that syntax as it contradicts usual 'heredoc' definition used in bash, etc.
