### ISSUE TITLE
resource "kubernetes_deployment" not avialable

### ISSUE THREAD

**Issue by tete17** [VladRassokhin/intellij-hcl#177]
Thank you for opening an issue.
In this template paragraph text could be removed, however please retain headers.

### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`) 
CLion 2018.3.1
Build #CL-183.4588.63, built on December 4, 2018
Licensed to Miguel Sacristan Izcue
Subscription is active until May 31, 2019
JRE: 1.8.0_152-release-1343-b16 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-42-generic
 - [x] intellij-hcl plugin version (`Settings->Plugins`)
0.6.12
 - [x] Terraform version (`terraform -v`)
v0.11.10

### Terraform Configuration Files
```hcl
provider "aws" {
  region  = "eu-central-1"
  version = "~> 1.49"
}

provider "kubernetes" {
  version = "~> 1.4"
}
resource "kubernetes_deployment" "test" {

}
```

### Expected Behavior
It should know what a kubernetes_deployment is and help with the syntax

### Actual Behavior
It is not recognise as a viable option

### Steps to Reproduce
Try to create a a resource starting with kubernetes and the deployment will not be a part of the auto completion

Thanks in Advance

**Comment by VladRassokhin** [comment]
Fixed in 0.6.13
