### ISSUE TITLE
Terraform fmt needs to leave tfvars alone

### ISSUE THREAD

**Issue by idcmp** [VladRassokhin/intellij-hcl#181]
# Setup
1. Have a project with a .tf file and a .tfvars file; both modified locally.
1. Enable "Terraform fmt" in the Git commit dialog.

# Result

* Both the .tf and .tfvars files are formatted.

# Expected result

* Only the .tf file is formatted

# Related Issue

* https://github.com/VladRassokhin/intellij-hcl/issues/162

**Comment by matschaffer** [comment]
Looks like 0.12.0 will check both tf and tfvars files (https://github.com/hashicorp/terraform/blob/master/command/fmt.go#L136).

I've closed #162 as invalid. @idcmp or @VladRassokhin - you may want to close this one too

**Comment by VladRassokhin** [comment]
@matschaffer thanks for information
