### ISSUE TITLE
Data Source google_compute_instance is not available 

### ISSUE THREAD

**Issue by MastaPA** [VladRassokhin/intellij-hcl#184]
### Installation details
 IntelliJ IDEA 2018.3.1 (Community Edition)
Build #IC-183.4588.61, built on December 4, 2018
JRE: 1.8.0_152-release-1343-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.2

 intellij-hcl plugin version v0.6.12
 
Terraform version Terraform v0.11.11

### Expected Behavior
Data Source should be available, in-line tips should be available

### Actual Behavior
Plugin does not provide any help, tips, etc when you trying create Data Source google_compute_instance

**Comment by VladRassokhin** [comment]
Fixed in 0.6.13
