### ISSUE TITLE
Support spell checking

### ISSUE THREAD

**Issue by aewhite** [VladRassokhin/intellij-hcl#185]
The spell checking inspection doesn't seem to work for .tf files. I believe it needs to be enable via the plugin.xml file as described by [this SO answer](https://stackoverflow.com/a/12445649).

**Comment by G-Rath** [comment]
This would be super useful; looking at the [code](https://github.com/JetBrains/intellij-community/blob/master/java/java-impl/src/com/intellij/spellchecker/JavaSpellcheckingStrategy.java), it seems fairly straightforward to add quick support for things like comments & strings.

I'd be happy to take a crack at it, but would have no idea how to write the tests :joy:

Personally, I'd be super happy if spell-checking was enabled for comments, b/c then we're be able to at least comment everything out to do a quick spell check.

For me, "basic" spelling checking support would cover:
  * comments
  * HEREDOC
  * Strings

And then "advanced" would include things like resource names.

**Comment by VladRassokhin** [comment]
Initial spellchecking support will be available in version 0.7.9
