### ISSUE TITLE
aws_dynamodb_table flags read/write capacity as required but is optional

### ISSUE THREAD

**Issue by matschaffer** [VladRassokhin/intellij-hcl#188]
### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - IDE version (`Help->About->Copy to Clipboard`)

IntelliJ IDEA 2018.3 (Ultimate Edition)
Build #IU-183.4284.148, built on November 21, 2018
Licensed to Mat Schaffer
You have a perpetual fallback license for this version
Subscription is active until January 15, 2020
JRE: 1.8.0_152-release-1343-b15 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.2

 - intellij-hcl plugin version (`Settings->Plugins`)
v0.6.12

 - Terraform version (`terraform -v`)
v0.11.11

### Terraform Configuration Files
```hcl
resource "aws_dynamodb_table" "locking" {
  name         = "${var.base_name}-terraform-${var.region}"
  hash_key     = "LockID"
  billing_mode = "PAY_PER_REQUEST"

  attribute {
    name = "LockID"
    type = "S"
  }
}
```

### Exception
```text
Missing required properties: read_capacity, write_capacity less... (⌘F1) 
Inspection info: Reports blocks with missing required properties
```

### Expected Behavior
Nothing flagged

### Actual Behavior
Flagged "missing" properties

**Comment by VladRassokhin** [comment]
Please update to latest version of plugin

**Comment by matschaffer** [comment]
Whoops! Sorry, still getting used to the new plugins UI in IntelliJ and thought it was up-to-date. Latest release looks great.

**Comment by VladRassokhin** [comment]
Just invoke `Help -> Check for Updates` action ;)
