### ISSUE TITLE
'Convert to HCL2' issue with lists

### ISSUE THREAD

**Issue by mkuzmin** [VladRassokhin/intellij-hcl#192]
### Installation details
IntelliJ IDEA 2019.1 Snapshot (Ultimate Edition)
Build #IU-191.4738.6, built on January 29, 2019
macOS 10.14.2

intellij-hcl plugin version 0.6.210

### Terraform Configuration Files
My HCL1 code has the next string:

```hcl
size = "${data.vsphere_virtual_machine.base.disks.0.size}"
```

I apply `Convert to HCL2 expression` quick fix.

### Expected Behavior
`size = data.vsphere_virtual_machine.base.disks[0].size`

### Actual Behavior
`size = data.vsphere_virtual_machine.base.disks`

**Comment by VladRassokhin** [comment]
Fixed in next build
