### ISSUE TITLE
support aws_eks_cluster_auth

### ISSUE THREAD

**Issue by llamahunter** [VladRassokhin/intellij-hcl#195]
### Installation details
 - [IntelliJ IDEA 2018.3.4 (Ultimate Edition)
Build #IU-183.5429.30, built on January 28, 2019
JRE: 1.8.0_152-release-1343-b26 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3 ] IDE version (`Help->About->Copy to Clipboard`)
 - [v0.6.13 ] intellij-hcl plugin version (`Settings->Plugins`)
 - [0.11.11 ] Terraform version (`terraform -v`)

### Terraform Configuration Files
```hcl
data "aws_eks_cluster_auth" "eks" {
  name = "${aws_eks_cluster.eks.name}"
}
```

### Expected Behavior
References to `aws_eks_cluster_auth.eks.token` should be ok

### Actual Behavior
References are flagged as 'Unresolved reference'

I think this is a fairly new schema element.  Appears to be first released in the aws provider in version 1.58.0 (February 08, 2019)

**Comment by VladRassokhin** [comment]
Fixed in 0.6.14
