### ISSUE TITLE
Unknown block type for Nomad job block names

### ISSUE THREAD

**Issue by andye2004** [VladRassokhin/intellij-hcl#198]
Thank you for opening an issue.
In this template paragraph text could be removed, however please retain headers.

### Prerequisites
 - [Y] Ensure you have latest version of plugin installed
 - [Y] Search for possible issue duplicates

### Installation details
 - [2018.3.4] IDE version
 - [v0.6.13] intellij-hcl plugin version
 - [N/A] Terraform version

### Exception
```text
None
```

### Expected Behavior
Nomad job configuration stanza names should be correctly identified / auto-completion suggestions made

### Actual Behavior
Lexical analysis states: Unknown block type for Nomad job stanza names

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a new file called job.nomad and add the below job configuration

```text
job "caller-service-job" {
  datacenters = ["dc1"]
  type = "service"
}
```
2. If real time analysis is enabled the `job` will be highlighted and the `Unknown block type...` message will be displayed when you hover over it. Alternatively, right click in the file and select `Analyze/Inspect Code` and then click `OK` and the `Inspection Results` tab will appear and with the `Unknown block type...` results.

NOTE: `Unknown block type...` is returned for all Nomad job stanza names.

**Comment by VladRassokhin** [comment]
Normally Terraform-related inspections are disabled for .nomad files. 
Please ensure that in your IDE 'nomad' files are associated with 'HashiCorp Configuration Language' language, not 'Terraform' one.
Could be checked at Preferences -> Editor -> File Types

**Comment by andye2004** [comment]
@VladRassokhin, That was exactly the issue. Thanks for the help!

I'm assuming there is no auto-completion for the nomad schema / dictionary?

**Comment by VladRassokhin** [comment]
For now unfortunately there's no autocompletion and other features for Nomad :(
