### ISSUE TITLE
Resource names starting with integer marked as error

### ISSUE THREAD

**Issue by rfpludwick** [VladRassokhin/intellij-hcl#199]
Thank you for opening an issue.
In this template paragraph text could be removed, however please retain headers.

### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`)
```
PhpStorm 2018.3.4
Build #PS-183.5429.47, built on February 8, 2019
JRE: 1.8.0_152-release-1343-b26 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3
```
 - [x] intellij-hcl plugin version (`Settings->Plugins`)
`v0.6.13`
 - [x] Terraform version (`terraform -v`)
```
Terraform v0.11.11
+ provider.aws v2.0.0
```

### Terraform Configuration Files
```hcl
resource "aws_default_subnet" "2a" {
//...
}

resource "aws_default_network_acl" "default" {
  subnet_ids = [
    "${aws_default_subnet.2a.id}",
//...
  ]
//...
}
```

### Exception
```text
Error:(47, 28) '(', <operator> or '}' expected, got 'a'
```

### Expected Behavior
The plugin should not mark this as an error.

### Actual Behavior
It was marked as an error, and also caused a review dialog in VCS interactions.

### Steps to Reproduce
Have a config much like the one I posted above.

**Comment by VladRassokhin** [comment]
Will fix, though I'd not recommend to use such names since they're not supported in Terraform 0.12 and will produce error 
>A name must start with a letter and may contain only letters, digits, underscores, and dashes.
