### ISSUE TITLE
Can't locate module locally

### ISSUE THREAD

**Issue by Tom-Mann** [VladRassokhin/intellij-hcl#204]
Thank you for opening an issue.
In this template paragraph text could be removed, however please retain headers.

### Prerequisites
 - [done] Ensure you have latest version of plugin installed
 - [done ] Search for possible issue duplicates

### Installation details
 - [PyCharm 2019.1.1 (Professional Edition) Build #PY-191.6605.12, built on April 3, 2019
JRE: 11.0.2+9-b159.34 amd64 JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0 ] IDE version (`Help->About->Copy to Clipboard`)
 - [ v0.6.14] intellij-hcl plugin version (`Settings->Plugins`)
 - [ v0.11.13] Terraform version (`terraform -v`)

### Terraform Configuration Files
```hcl
module vmhost {
  source = "git::https://bitbucket.somedomain.net/scm/magic/project.git//magic/modules/vmhost"
```

### Exception
module is highlighted yellow and the error "Can't locate module locally: Terraform Module 'vmhost' with source "git::https://bitbucket.somedomain.net/scm/magic/project.git//magic/modules/vmhost"  directory not found locally, use 'terraform get' to fetch modules. 

### Expected Behavior
It should handle the sub folder checkout from git

### Actual Behavior
It reports it is unable to find the directory

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. check code into git/bitbucket with multiple folders for modules
2. reference one folder as per above as a source

**Comment by VladRassokhin** [comment]
Does it work after invoking `terraform get` in console or from quick fix?
Please run `terraform get` and include content of `.terraform/modules/modules.json` here.

**Comment by Tom-Mann** [comment]
Thought I had mentioned it, but I have ran it multiple times. content of the json is
{"Modules":[{"Source":"git::https://bitbucket.somedomain.net/scm/magic/project.git//magic/modules/vmlinux","Key":"1.vmlinux;git::https://bitbucket.somedomain.net/scm/magic/project.git//magic/modules/vmlinux","Version":"","Dir":".terraform/modules/b5c8bc6b1ec57ed2bd2f5fc20e6f5cd5","Root":"magic\\modules\\vmlinux"}]}

**Comment by VladRassokhin** [comment]
Does `"Root"` in modules.json have `\m`/`\v` or `\\m`/`\\v`? Just trying to understand what's wrong with escaping.

**Comment by VladRassokhin** [comment]
Ok. Seems it's related to file path separators, API I'm using to resolve relative path expect forward slashes only, will fix and release update ASAP

**Comment by sarkis** [comment]
I'm experiencing this issue with:
GoLand 2019.2.3
Intellij-hcl plugin 0.7.7
Terraform 0.12.10

Even when I run a `terraform get` in the directory I still get:

```
Can't locate module locally: Terraform Module 'vpc1' with source 'terraform-aws-modules/vpc/aws' directory not found locally use terraform get to fetch modules.
```

Here is my modules.json if that helps:

```
{"Modules":[{"Key":"","Source":"","Dir":"."},{"Key":"vpc1","Source":"terraform-aws-modules/vpc/aws","Version":"2.17.0","Dir":".terraform/modules/vpc1/terraform-aws-modules-terraform-aws-vpc-5358041"}]}
```

**Comment by barrywhart** [comment]
I'm still seeing what appears to be the same issue.

I ran `terraform get` using Quick Fix. My `.terraform/modules/modules/json` file looks like:
```
{"Modules":[{"Key":"support-auto-tag","Source":"../../modules/rsg/project","Dir":"../../modules/rsg/project"},{"Key":"support-auto-tag-dataflow-extras","Source":"git::https://git.rsglab.com/rsg/datascience-tf-dataflow-extras.git?ref=v2.0","Dir":".terraform/modules/support-auto-tag-dataflow-extras"},{"Key":"support-auto-tag-extras","Source":"../../modules/rsg/datascience/project-extras","Dir":"../../modules/rsg/datascience/project-extras"},{"Key":"support-auto-tag-extras.bigquery-readers","Source":"../bigquery-readers","Dir":"../../modules/rsg/datascience/bigquery-readers"},{"Key":"","Source":"","Dir":"."},{"Key":"constants","Source":"../../modules/rsg/datascience/constants","Dir":"../../modules/rsg/datascience/constants"}]}
```

I am using PyCharm with version 0.7.7 of the plugin, released October 9, 2019.

**Comment by zswanson** [comment]
Ditto, same problem on macos using:
Terraform v0.12.24
+ provider.aws v2.56.0
HCL plugin 0.7.7
PyCharm CE 2019.3.4

**Comment by VladRassokhin** [comment]
@barrywhart @zswanson If you're using PyCharm please ensure you don't have 'attached' projects or wait to plugin 0.7.8

**Comment by zswanson** [comment]
@VladRassokhin Ok that's probably my issue, I have multiple terraform 'projects' (all related to our system) that I have open in a single view.

**Comment by barrywhart** [comment]
I have a bunch of projects open as well. One or two are Terraform and the rest are Python.

**Comment by barrywhart** [comment]
Thanks for the update!

**Comment by bergbrains** [comment]
This worked for me, though I do like to have all of the TF projects in one Pycharm project....It's nice to have this functionality.  Would be a great fix.

**Comment by TheNomet** [comment]
Hi @VladRassokhin 
I am having the same problem with Pycharm professional and HCL plugin 0.7.10 on Unix.
```
{"Modules":[{"Key":"","Source":"","Dir":"."},{"Key":"cluster","Source":"git::ssh://git@github.com/myproject.git//modules/cluster/?ref=my_branch","Dir":".terraform/modules/cluster/modules/cluster"}]}
```
Paths seem correct to me, but the interpreter is not able to locate the modules, unfortunately.
Could you please help? Thank you very much.

**Comment by jzburns** [comment]
I still have this issue. This seems to have started recently:

Webstorm: Build #WS-213.5744.224, built on November 27, 2021
Plugin 0.7.14
OS: Arch Linux
Error Cannot locate module locally: Unknown reason 

```
module "gce-container-c1" {
  source = "terraform-google-modules/container-vm/google"
  version = "~> 2.0"
  container = {
    image = "eu.gcr.io/XXXX"
  }
  restart_policy = "Always"
}
```

Any workarounds?

**Comment by baguilarq** [comment]
> I still have this issue. This seems to have started recently:
> 
> Webstorm: Build #WS-213.5744.224, built on November 27, 2021 Plugin 0.7.14 OS: Arch Linux Error Cannot locate module locally: Unknown reason
> 
> ```
> module "gce-container-c1" {
>   source = "terraform-google-modules/container-vm/google"
>   version = "~> 2.0"
>   container = {
>     image = "eu.gcr.io/XXXX"
>   }
>   restart_policy = "Always"
> }
> ```
> 
> Any workarounds?

which terraform version? It's happening to me too. I've 1.1.0

**Comment by zbmowrey** [comment]
> which terraform version? It's happening to me too. I've 1.1.0 right now, but I was using 1.0.11 and had no issues

I can confirm an upgrade from 1.0.11 to 1.1.0 triggered this issue for me. I'm going to walk through each version to see where the break is.

**Comment by yuriipolishchuk** [comment]
same issue with 1.1+, works fine on 1.0.11

**Comment by cagataygurturk** [comment]
Same same

**Comment by midu-git** [comment]
Any news on this issue? Seems like terraform has changed the "Source" entry in modules.json moving from 1.0.11 to 1.1+. E.g.:
1.1.2
```
{
      "Key": "some_sg",
      "Source": "terraform-aws-modules/security-group/aws",
      "Version": "4.7.0",
      "Dir": ".terraform/modules/some_sg"
}
```
1.0.11
```
{
      "Key": "some_sg",
      "Source": "registry.terraform.io/terraform-aws-modules/security-group/aws",
      "Version": "4.7.0",
      "Dir": ".terraform/modules/some_sg"
}
```

**Comment by midu-git** [comment]
A solution for the above issue can be found here:
https://github.com/VladRassokhin/intellij-hcl/issues/365#issuecomment-996019841
