### ISSUE TITLE
Modules not detected correctly in 'attached projects' in PyCharm

### ISSUE THREAD

**Issue by VladRassokhin** [VladRassokhin/intellij-hcl#205]
Any update on this? the problem is still present in 2019.1 and 2018.3.6

Edit:
Apparently the issue happens when working with attached projects in PyCharm, when opening the project in a new window, the errors are gone.

_Originally posted by @azelezni in https://github.com/VladRassokhin/intellij-hcl/issues/170#issuecomment-496423960_

**Comment by MXWest** [comment]
In `2019.2` I am experiencing the errors when opening as an attached project. Opening the project in a new window does "fix" the problem.

**Comment by sarkis** [comment]
Experiencing the same problem with GoLand 2019.2.3, projects in their own window works fine and attached projects are not detecting modules correctly.

**Comment by VladRassokhin** [comment]
Will be fixed in next plugin release
