### ISSUE TITLE
Unresolved references to custom types attributes in TF 0.12

### ISSUE THREAD

**Issue by bowczarek** [VladRassokhin/intellij-hcl#209]
I noticed that input variables declared as custom types with different attributes cannot be later resolved `object({<ATTR NAME> = <TYPE>, ... })` :

example:
![image](https://user-images.githubusercontent.com/7836378/58686559-70ea4f80-837f-11e9-9e94-badc1c4eb7a1.png)

This is also valid for ***.tfvars** files, example:
![image](https://user-images.githubusercontent.com/7836378/58686440-1cdf6b00-837f-11e9-812f-a84b94848521.png)

**Comment by VladRassokhin** [comment]
Fixed in 0.7.2
