### ISSUE TITLE
Support provider alias as data type with tf 0.12

### ISSUE THREAD

**Issue by albuch** [VladRassokhin/intellij-hcl#210]
### Installation details
 - [x] IDE version: IntelliJ IDEA 2019.1.3 (Ultimate Edition) Build #IU-191.7479.19, built on May 28, 2019
 - [x] intellij-hcl plugin version: v0.7.0
 - [x] Terraform version: 0.12.0

### Terraform Configuration Files
```hcl
provider "aws" {
  alias   = "iam"
  region  = var.region
  version = "~> 2.12.0"
}

resource "aws_iam_user" "test" {
  name          = "test"
  path          = "/"

  provider = aws.iam
}

module "test" {
  source = "./modules/test"
  providers = {
    aws.target = aws.iam
  }
}
```

### Exception
```text
For resource:
Unresolved reference iam

For module:
<property> expected, got '.'
Unresolved reference iam
<identifier> or <string literal> expected, got '}'
```

### Expected Behavior
Plugin should not report a validation error for provider alias data type when not defined as a string literal.
For Modules provider target alias should not be reported as an error if not defined as a string literal.

### Actual Behavior
Provider alias is reported as error, see exception section.

**Comment by VladRassokhin** [comment]
Fixed in 0.7.1, will be released shortly
