### ISSUE TITLE
Argument names must not be quoted in TF 0.12

### ISSUE THREAD

**Issue by haidaraM** [VladRassokhin/intellij-hcl#211]
The code snippet generated by the IDE contains quote on attribute names that causes terraform plan/fmt/validate to fail. See below for an example with `aws_dynamodb_table` resource.

### Installation details
 - [X] IDE version: IntelliJ IDEA 2019.1.3 (Ultimate Edition) Build #IU-191.7479.19, built on May 28, 2019
 - [X] intellij-hcl plugin version: v0.7.0
 - [X] Terraform version : Terraform v0.12.0, provider.aws v2.12.0 

### Terraform Configuration Files
```hcl
resource "aws_dynamodb_table" "test" {
  hash_key = ""
  name = ""

  "attribute" {
    name = ""
    type = ""
  }
}
```

### Exception
Inside the IDE: Right Click -> Terraform Tools -> Terraform fmt file
```bash

Error: Invalid argument name

  on main.tf line 5:
  (source code not available)

Argument names must not be quoted.
```

### Expected Behavior
The plugin should not generate code with quoted argument names.

### Actual Behavior
The plugin generate a code with quoted argument names.

### Steps to Reproduce
1. Create a `main.tf`
2. Start typing `resource aws_dynamodb` and let IDE autocomplete
3. Inside the IDE: Right Click inside the file -> Terraform Tools -> Terraform fmt file or run `$ terraform fmt`. The output is slightly different when you use `$ terraform validate`.

**Comment by VladRassokhin** [comment]
Fixed, will be available in 0.7.2
