### ISSUE TITLE
Object output values when member referenced show as unresolved reference

### ISSUE THREAD

**Issue by jdillon** [VladRassokhin/intellij-hcl#213]
idea version: IntelliJ IDEA 2019.1.3 (Ultimate Edition)
intellij-hcl plugin version: 0.7.1
terraform version: Terraform v0.12.0

* * *

With a module output which exposes a complex object like a resource:

```hcl
output "events_topic" {
  value = aws_sns_topic.events
}
```

When referenced shows unresolved reference for member reference:

```hcl
module "console_resources" {
  source = "../../modules/resources"
  topic_arn = module.resources.events_topic.arn
}
``` 

Shows error marker of: "Unresolved reference arn"

This however is valid 0.12 syntax IIUC (and terraform seems to behave as expected as well).

**Comment by VladRassokhin** [comment]
Fixed, will be available in 0.7.2
