### ISSUE TITLE
Modules with souce of "Generic Git Repository" wont resolve locally

### ISSUE THREAD

**Issue by nedjs** [VladRassokhin/intellij-hcl#216]
Remote git repositories are not resolved locally once downloaded. This is using the source type of a [generic git repository](https://www.terraform.io/docs/modules/sources.html#generic-git-repository)

### Installation details
 - IDE version
JetBrains Rider 2019.1.1
Build #RD-191.6733.985, built on May 1, 2019
Licensed to Ned Stuart
Subscription is active until June 6, 2019
JRE: 1.8.0_202-release-1483-b49 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

 - intellij-hcl plugin version 
v0.7.2 (observed on previous versions as well)

 - Terraform version
v0.11.7

### Terraform Configuration Files
```hcl
// Basic module I made in a public repo containing 1 variable. But any repository will do
// Warning: Can't locate terraform locally: Terraform module..... use `terraform get`
module "sample" {
  source = "git::https://github.com/nedjs/sample-terraform-module.git"
}
```

### Expected Behavior
The module to be located at its local path.

### Actual Behavior
Module is never found locally (despite running `terraform get`). The warning stating cannot locate module never goes away. Terraform itself resolves the module fine.

**Comment by VladRassokhin** [comment]
Looks like Terraform 0.12 uses yet another schema for `.terraform/modules/modules.json` 😞

**Comment by nedjs** [comment]
Was able to make it work with some slight code changes in `ModuleDetectionUtil.kt`:

```kt
// line ModuleDetectionUtil.kt:97
// if (isRegistrySource(source)) {
if (isRegistrySource(source) || isRemoteSource(source)) {
}
...
  private fun isRemoteSource(source: String): Boolean {
    return URI(source).scheme.toLowerCase() in listOf("git", "hc", "s3")
  }
```

However given that seems almost to simple im not sure of the ramifications that has and wasn't comfortable putting in a pull request for it without further investigation.

**Comment by VladRassokhin** [comment]
I've added support for Terraform 0.12 modules descriptor (`.terraform/modules/modules.json`), though it should also work for Terraform 0.11, please check once 0.7.3 is released.
