### ISSUE TITLE
Support for templatefile function

### ISSUE THREAD

**Issue by petitg1987** [VladRassokhin/intellij-hcl#219]
### Installation details
* IntelliJ: IntelliJ IDEA 2019.1.3 (Ultimate Edition)
* IntelliJ HCL plugin: 0.7.2
* Terraform: 0.12.0

### Exception
Syntax error displayed on "templatefile" function when used in a correct way (https://www.terraform.io/docs/configuration/functions/templatefile.html)
![templatefile](https://user-images.githubusercontent.com/11319935/58979479-748e3400-87ce-11e9-91df-292b6b99a7f8.png)

### Expected Behavior
No syntax error

**Comment by VladRassokhin** [comment]
Fixed. Will be available in 0.7.3.
