### ISSUE TITLE
self.public_ip flagged as invalid

### ISSUE THREAD

**Issue by meriouma** [VladRassokhin/intellij-hcl#220]
### Prerequisites
 - [X] Ensure you have latest version of plugin installed
 - [X] Search for possible issue duplicates

### Installation details
 - [X] IDE version (`Help->About->Copy to Clipboard`)
```
IntelliJ IDEA 2019.1.3 (Ultimate Edition)
Build #IU-191.7479.19, built on May 28, 2019
JRE: 1.8.0_202-release-1483-b58 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```
 - [X] intellij-hcl plugin version (`Settings->Plugins`)  `0.7.2`
 - [x] Terraform version (`terraform -v`) `0.12.0`

### Terraform Configuration Files
```hcl
connection {
        host = self.public_ip
        user = "admin"
        type = "ssh"
        agent = true
}
```

### Expected Behavior
What should have happened?
According to [the upgrade guide](https://www.terraform.io/upgrade-guides/0-12.html#default-settings-in-connection-blocks), self.public_ip is now required in connection block, it should be valid.

### Actual Behavior
What actually happened?
`public_ip` is in red

**Comment by VladRassokhin** [comment]
Fixed. Will be available in 0.7.3
