### ISSUE TITLE
do not suggest HCL2 replacement for required_version 0.11 

### ISSUE THREAD

**Issue by mdaniel** [VladRassokhin/intellij-hcl#225]
### Prerequisites
 - [X] Ensure you have latest version of plugin installed
 - [X] Search for possible issue duplicates

### Installation details
 - [X] IDE version (`Help->About->Copy to Clipboard`)
    IntelliJ IDEA 2019.2 EAP (Ultimate Edition)
    Build #IU-192.4787.16, built on June 6, 2019
 - [X] intellij-hcl plugin version (`Settings->Plugins`) 0.7.3 Jun 09, 2019
 - [X] Terraform version (`terraform -v`) Terraform v0.11.14

### Terraform Configuration Files
```hcl
terraform {
  required_version = "0.11.14"
}
variable "region" {}
provider "aws" {
  region  = "${var.region}"
  version = "~> 2.1"
}
```

### Expected Behavior

No HCL2 interpolation is offered since the file explicitly says to use terraform "0.11.x"

### Actual Behavior

the plugin suggests replacing the interpolation with HCL2 but one cannot fulfill that suggestion, permanently placing the file in "yellow" status:
![image](https://user-images.githubusercontent.com/22526/59477427-04a12e80-8e0a-11e9-9ced-a69199b869cf.png)

### Steps to Reproduce

1. Open file
2. Observe warning

**Comment by VladRassokhin** [comment]
Fixed for directories with 'terraform.required_version' property, will be available in next plugin release.
