### ISSUE TITLE
String Interpolation missing in .hcl files

### ISSUE THREAD

**Issue by apottere** [VladRassokhin/intellij-hcl#226]
### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`)
 - [x] intellij-hcl plugin version (`Settings->Plugins`)
 - [x] Terraform version (`terraform -v`)

IntelliJ IDEA 2019.2 EAP (Ultimate Edition)
Build #IU-192.5118.30, built on June 13, 2019
HCL Plugin: 0.7.3
Terraform v0.12.1

### Terraform Configuration Files
```hcl
block {
  test = "${functioncall("")}"
}
```

### Expected Behavior
String interpolations are hilighted in `.hcl` files

### Actual Behavior
![image](https://user-images.githubusercontent.com/1980504/59546075-3f809080-8ef6-11e9-90e6-e7f732b22e87.png)

### Steps to Reproduce
Use string interpolation anywhere in a `.hcl` file

Interpolation works if file is renamed to `.tf`:
![image](https://user-images.githubusercontent.com/1980504/59546087-64750380-8ef6-11e9-80bc-e154984e85aa.png)

It looks like per #2 this is intentional behavior, however interpolations are part of the HCL spec: https://github.com/hashicorp/hcl2/blob/master/hcl/hclsyntax/spec.md#template-interpolations

It seems like interpolation should be added to strings in `.hcl` files, along with any relevant inspections.

**Comment by VladRassokhin** [comment]
Yep, that was done intentionally in times of HCL1, with HCL2 that seems no longer needed, will fix

**Comment by VladRassokhin** [comment]
Enabled interpolations for all hcl files. Will be available in next release.

**Comment by apottere** [comment]
Thanks!

**Comment by apottere** [comment]
Hey, just tested this out in the latest release (0.7.4).  It looks like there's no longer a syntax error at the end of the line, but the hilighting and inspections are still missing:
![image](https://user-images.githubusercontent.com/1980504/60193575-ea058700-9805-11e9-9255-fd24a8370b80.png)

**Comment by supersmile2009** [comment]
Hi @VladRassokhin! It doesn't seem to be working even on 0.7.10. Did something issue prevent this feature from finally getting into the release?
