### ISSUE TITLE
Terraform HCL2: dynamic resource doesn't work properly

### ISSUE THREAD

**Issue by hmnp** [VladRassokhin/intellij-hcl#227]
### Prerequisites
 - [X] Ensure you have latest version of plugin installed
 - [X] Search for possible issue duplicates

### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`)
```
IntelliJ IDEA 2019.1.3 (Community Edition)
Build #IC-191.7479.19, built on May 28, 2019
JRE: 1.8.0_202-release-1483-b58 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5
```
 - [x] intellij-hcl plugin version (`Settings->Plugins`)
```
v0.7.3,v0.7.4
```
 - [x] Terraform version (`terraform -v`)
```
0.12.2
```

### Terraform Configuration Files
```hcl
resource "aws_codebuild_project" "default" {
  name        = local.project_name
  description = local.project_description

  dynamic "source" {
    for_each = [local.source_code]
    content {
      buildspec           = lookup(source.value, "buildspec", null)
      git_clone_depth     = lookup(source.value, "git_clone_depth", null)
      insecure_ssl        = lookup(source.value, "insecure_ssl", null)
      location            = lookup(source.value, "location", null)
      report_build_status = lookup(source.value, "report_build_status", null)
      type                = source.value.type

      dynamic "auth" {
        for_each = lookup(source.value, "auth", [])
        content {
          resource = lookup(auth.value, "resource", null)
          type     = auth.value.type
        }
      }
    }
  }
...
}
```

### Expected Behavior
It should show the resource normally, but it shows it highlighted (like when we add an external module). I've uploaded an image with an example.

When I run `terraform apply` it works just fine.

### Actual Behavior
<img width="626" alt="Screenshot 2019-06-21 at 21 41 47" src="https://user-images.githubusercontent.com/40466699/59947401-6f3b1580-946d-11e9-9420-69cec92841c1.png">

### Steps to Reproduce
1. Add a resource.
2. Inside the resource, add a `dynamic` block.

**Comment by VladRassokhin** [comment]
@hmnp Does this issue reproduces with plugin version 0.7.4?

**Comment by hmnp** [comment]
Hi @VladRassokhin 

I've just checked and the issue is still there. I've confirmed the version and it's the 0.7.4

**Comment by VladRassokhin** [comment]
Could you please share example of 'local.source_code' definition? I'd like to know it structure.

**Comment by VladRassokhin** [comment]
Looks like I've finally fixed cause, will be available in 0.7.5.

**Comment by alexejk** [comment]
Just got hit by this one as well - happy to see this is fixed for 0.7.5 as well! 👍

**Comment by alexejk** [comment]
@VladRassokhin I believe there is still issue in the dynamic resource to some extend. The `<iterator>.value` is marked red for some reason.

![image](https://user-images.githubusercontent.com/104794/62207550-af5ab580-b394-11e9-8d04-34ea5d2226c3.png)

Based on https://www.terraform.io/docs/configuration/expressions.html 

> The iterator object has two attributes:
>  * key is the map key or list element index for the current element. If the for_each exression produces a set value then key is identical to value and should not be used.
>  * value is the value of the current element.

**Comment by VladRassokhin** [comment]
@alexejk It's inside 'aws_ec2_fleet' resource, right?

**Comment by VladRassokhin** [comment]
Thanks, @alexejk, turns out there was still bug when dynamic block located not directly under resource. Fixed now, will be available in next update.

**Comment by alexejk** [comment]
Its on the aws_launch_template in my case. But yes it's nested under several sub blocks.

Thanks for fixing it so fast! Really useful plugin for me (and much more powerful than VSCode one).

**Comment by hmnp** [comment]
Hi @VladRassokhin 
On my side it's working fine now 👍
