### ISSUE TITLE
No support for new types of version 12

### ISSUE THREAD

**Issue by timtam76** [VladRassokhin/intellij-hcl#228]
Thank you for opening an issue.
In this template paragraph text could be removed, however please retain headers.

### Prerequisites
 - [ ] Ensure you have latest version of plugin installed
 - [ ] Search for possible issue duplicates

### Installation details
 - [ ] IDE version (`Help->About->Copy to Clipboard`)
 - [ ] intellij-hcl plugin version (`Settings->Plugins`)
 - [ ] Terraform version (`terraform -v`)

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configuration here - for large Terraform configs,
# please use a gist (https://gist.github.com) and share a link. 
```

### Exception
```text
For exceptions paste exception stack trace here. If it's huge one - use gist.
```

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Place cursor somewhere
2. Invoke completion.

**Comment by VladRassokhin** [comment]
So this is example of stupidiest issue ever open on GitHub. And then they ask "Why don't you believe in open-source and users sanity?"
