### ISSUE TITLE
Missing required properties after resource change in the provider

### ISSUE THREAD

**Issue by anouvel** [VladRassokhin/intellij-hcl#229]
### Installation details
 - [x] IDE version (`2019-1-3`)
 - [x] intellij-hcl plugin version (`v-0.7.4`)
 - [x] Terraform version (`0.12.3`)

### Terraform Configuration Files

```hcl
resource "aws_ec2_transit_gateway_route" "this" {
  destination_cidr_block         = ""
  transit_gateway_route_table_id = ""
  blackhole                      = true
}
```

### Expected Behavior

It should raise no error. The attribute `transit_gateway_attachment_id` is now optional, because of the support of the `blackhole` attribute.

### Actual Behavior

The plugin still required the `transit_gateway_attachment_id` in the completion.
I don't know how the documentation is linked to the provider, so this issue is probably more a question than a real feature request...!

<img width="464" alt="Screenshot 2019-07-07 at 10 35 01 AM" src="https://user-images.githubusercontent.com/8018172/60765967-ec3bd100-a0a2-11e9-95d3-514107a0c8fd.png">

Thanks!

**Comment by VladRassokhin** [comment]
Will be fixed in next plugin release: I've just [updated metadata](https://github.com/VladRassokhin/terraform-metadata)
