### ISSUE TITLE
HCL2 Syntax for Maps is falsely marked as invalid

### ISSUE THREAD

**Issue by alexejk** [VladRassokhin/intellij-hcl#230]
The new Map (introduced in Terraform 0.12) creation syntax is not accepted by the plugin.

More details: https://www.terraform.io/docs/configuration/functions/map.html
See deprecation warning of the `map()` function and recommendation to use a shorter syntax.

### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`)
``` IntelliJ IDEA 2019.2 EAP (Ultimate Edition)
Build #IU-192.5587.17, built on July 2, 2019
IntelliJ IDEA EAP User
Expiration date: August 1, 2019
Runtime version: 11.0.3+12-b304.10 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: 
Non-Bundled Plugins: Lombook Plugin, com.intellij.plugins.watcher, io.protostuff.protostuff-jetbrains-plugin, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, org.intellij.plugins.hcl, org.jetbrains.plugins.go-template, izhangzhihao.rainbow.brackets, org.jetbrains.plugins.go, com.intellij.kubernetes, org.toml.lang, org.rust.lang
```
 - [x] intellij-hcl plugin version (`Settings->Plugins`)
```
0.7.4
```
 - [x] Terraform version (`terraform -v`)
```
Terraform v0.12.3
+ provider.aws v2.18.0
```

### Terraform Configuration Files
```hcl
resource "aws_subnet" "public" {
  vpc_id            = "vpc-whatever"
  availability_zone = "us-west-1a"
  cidr_block        = "10.0.0./24"

  // This is where the problems is
  tags = merge(
    aws_vpc.main.tags,
    {
      "Public" = "true"

      "kubernetes.io/role/elb"         = "1"
	  "kubernetes.io/role/alb-ingress" = "1"

    }
  )
}
```

### Exception
N/A

### Expected Behavior
The syntax of TF 0.12 to define maps should be accepted by the plugin.

### Actual Behavior
Plugin marks the keys of the map, such as "Public" as invalid syntax, and states that Argument names must not be quoted. However the syntax is 100% valid and TF commands go through as expected.

### Steps to Reproduce
1. Copy-paste the above snippet (possible to drop parameters that do not matter)
2. Observe marking of keys in the map as "Arguments must not be quoted" (red underlines)

<img width="482" alt="image" src="https://user-images.githubusercontent.com/104794/60959869-4047ef00-a309-11e9-818c-1d7a217606ef.png">

**Comment by alexejk** [comment]
I believe this might be related to the fixes implemented for #211

**Comment by VladRassokhin** [comment]
Thanks for reporting, fixed, will be available in next update (0.7.5)

**Comment by alexejk** [comment]
@VladRassokhin would it be possible to know the planned release for 0.7.5 ?
I't s a quite frustrating / distracting issue and given the closed source nature of the updated plugin I can't build a nightly myself.

Or if you have a nightly URL potentially that could work too!
Much appreciated!

**Comment by VladRassokhin** [comment]
Hopefully this week, after I fix one-two more issues.

**Comment by jeffery** [comment]
I am using version 223.8214.6 of the plugin and this issue as described by the original reported is not resolved.
