### ISSUE TITLE
Support for IU-182.4129.33

### ISSUE THREAD

**Issue by frank815** [VladRassokhin/intellij-hcl#231]
Thank you for opening an issue.
In this template paragraph text could be removed, however please retain headers.

### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`)
 - [ ] intellij-hcl plugin version (`Settings->Plugins`)
 - [x] Terraform version (`terraform -v`)

### Terraform Configuration Files
N/A

### Exception
```text
Plugin 'HashiCorp Terraform / HCL language support' is incompatible with this installation
```
Intellij Version
```text
IntelliJ IDEA 2018.2.2 (Ultimate Edition)
Build #IU-182.4129.33, built on August 21, 2018

JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.5
```

### Expected Behavior
Plugin should be installed. 

### Actual Behavior
Plugin does not install. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. download plugin 
2. install plugin from disk

**Comment by VladRassokhin** [comment]
Please read plugin change notes ("What’s New" on plugin repo page) carefully. It states that:
* version 0.6.14.1 and newer requires at least IntelliJ Platform 2018.1
* version 0.7.0 and newer requires at least IntelliJ Platform 2019.1

There would be no new plugin versions for IntelliJ Platform 2018.2

**Comment by frank815** [comment]
Thank you for the reply. I’ll read those change logs a lot closer.
