### ISSUE TITLE
Autocompletion adds syntactically incorrect tag block

### ISSUE THREAD

**Issue by milo0** [VladRassokhin/intellij-hcl#233]
When adding a `tags` block by IntelliJ's autocompletion feature, the resulting block is inserted as:

`tags {}`

instead of the correct version

`tags = {}`

### Exception
```
Error: Unsupported block type

  on example.tf line 20, in resource "aws_s3_bucket" "teh_example_bucket":
  20:   tags {

Blocks of type "tags" are not expected here. Did you mean to define argument
"tags"? If so, use the equals sign to assign it a value.
```

### Steps to Reproduce
1. Inside a resource block type `ta`
2. Hit Enter or Tab to trigger autocompletion

### Installation details
 - [ ] IDE version: 2019.1.3
 - [ ] intellij-hcl plugin version: v0.7.4
 - [ ] Terraform version: v0.12.4

**Comment by VladRassokhin** [comment]
Fixed, will be available in 0.7.9
