### ISSUE TITLE
Invalid syntax for required_providers

### ISSUE THREAD

**Issue by bkmeneguello** [VladRassokhin/intellij-hcl#234]
### Prerequisites
 - [ ] Ensure you have latest version of plugin installed
 - [ ] Search for possible issue duplicates

### Installation details
 - [ ] IDE version (`Help->About->Copy to Clipboard`)
PyCharm 2019.1.3 (Community Edition)
Build #PC-191.7479.30, built on May 29, 2019
JRE: 11.0.2+9-b159.60 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-54-generic
 - [ ] intellij-hcl plugin version (`Settings->Plugins`)
v0.7.4
 - [ ] Terraform version (`terraform -v`)
Terraform v0.12.5

### Terraform Configuration Files
```hcl
terraform {
  required_version = ">= 0.12"
  required_providers {
    aws = ">= 2.20"
    local = "~> 1.2"
    null = "~> 2.1"
    random = "~> 2.1"
    template = "~> 2.1"
  }
}
```

### Exception
```text
<identifier>, <string literal> or '}' expected, got 'null'
```

### Expected Behavior
https://www.terraform.io/docs/configuration/terraform.html#specifying-required-provider-versions

### Actual Behavior
The syntax is invalid

**Comment by VladRassokhin** [comment]
Thank you for reporting, will be fixed in next plugin update (0.7.5 or so)
