### ISSUE TITLE
Unknow block required_providers

### ISSUE THREAD

**Issue by bkmeneguello** [VladRassokhin/intellij-hcl#237]
### Installation details
 - IDE version (`Help->About->Copy to Clipboard`)
PyCharm 2019.1.3 (Community Edition)
Build #PC-191.7479.30, built on May 29, 2019
JRE: 11.0.2+9-b159.60 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-54-generic
 - intellij-hcl plugin version (`Settings->Plugins`)
v0.7.5
 - Terraform version (`terraform -v`)
Terraform v0.12.5

### Terraform Configuration Files
```hcl
terraform {
  required_version = ">= 0.12"
  required_providers {
    aws = ">= 2.20"
    local = "~> 1.2"
    null = "~> 2.1"
    random = "~> 2.1"
    template = "~> 2.1"
  }
}
```

### Expected Behavior
No warning for `required_providers`

### Actual Behavior
```text
Unknown block type required_providers less... (Ctrl+F1) 
Inspection info: Reports blocks with unknown type (first literal)
```

**Comment by VladRassokhin** [comment]
Thank you for reporting, fixed, will be available in next release
