### ISSUE TITLE
A warning when a resource is created without a name

### ISSUE THREAD

**Issue by aryeguy** [VladRassokhin/intellij-hcl#238]
I would like to have a warning when a resource is created without a name

**Comment by mdaniel** [comment]
I came here looking for this issue, and I would advocate that it's not a warning, it's an error (at least as of 0.12.6):
> Error: Invalid resource name
>
>  on main.tf line 116, in resource "aws_iam_user_policy_attachment" "":
> 116: resource "aws_iam_user_policy_attachment" "" {

but IJ has a green checkmark

**Comment by VladRassokhin** [comment]
Fixed, will be available in next update.
