### ISSUE TITLE
Incorrect autocompletion for module variables type 

### ISSUE THREAD

**Issue by nick4fake** [VladRassokhin/intellij-hcl#239]
### Prerequisites
 - [*] Ensure you have latest version of plugin installed
 - [*] Search for possible issue duplicates

### Installation details
 - [*] IDE version: IDEA 2019.2
 - [*] intellij-hcl plugin version: 0.7.5
 - [*] Terraform version: v0.12.6

### Terraform Configuration Files
```hcl
variable "sg_sources_ids" {
  type = list(string)
}

...

module "ig-shared-resources" {
  source = "./ig-shared-resources"

  create           = var.create
  tags             = local.tags
  name             = local.name
  vpc_id           = var.vpc_id
  sg_master_id     = aws_security_group.k8s-master[0].id
  sg_sources_count = var.api_sg_count + 1
  sg_sources_ids   = local.api_sources_sgs_ids
  iam_boundary     = var.iam_boundary
}
```

### Exception
Not related.

### Expected Behavior
sg_sources_ids having correct type

### Actual Behavior
Type falls back to string

### Steps to Reproduce
Check screenshots:
![bug1](https://user-images.githubusercontent.com/1065993/62655386-79cf4280-b927-11e9-80ed-30584988ef96.PNG)
![bug1-1](https://user-images.githubusercontent.com/1065993/62655401-7f2c8d00-b927-11e9-91af-4b3e3105d472.PNG)

**Comment by VladRassokhin** [comment]
Fixed, will be available in 0.7.6
