### ISSUE TITLE
No autocompletion for variable types

### ISSUE THREAD

**Issue by nick4fake** [VladRassokhin/intellij-hcl#240]
### Prerequisites
 - [*] Ensure you have latest version of plugin installed
 - [*] Search for possible issue duplicates

### Installation details
 - [*] IDE version: IDEA 2019.2
 - [*] intellij-hcl plugin version: 0.7.5
 - [*] Terraform version: v0.12.6

### Terraform Configuration Files
```hcl
variable "foo" {
type = ...
}
```

### Exception
Not related.

### Expected Behavior
List of possible types being shown

### Actual Behavior
No suggestions

### Steps to Reproduce
Check screenshot:
![bug2](https://user-images.githubusercontent.com/1065993/62655489-b4d17600-b927-11e9-9c4d-1601ad5f502c.PNG)

**Comment by VladRassokhin** [comment]
Fixed, will be available in next update
