### ISSUE TITLE
Incorrect code cleanup suggestion around use of element function

### ISSUE THREAD

**Issue by loesak** [VladRassokhin/intellij-hcl#247]
Terraform code cleanup is providing a warning that this:

```hcl
element(data.aws_availability_zones.available.names, 15)
```

can be simplified, meaning equivalent, to:

```hcl
data.aws_availability_zones.available.names[15]
```

however this is not true as the index notation does not wrap elements when the index value is out of range of the list. However, the `element` function will wrap the list and always provide a value. Therefor these expressions cannot be simplified as suggested

### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`
```
IntelliJ IDEA 2019.2 (Ultimate Edition)
Build #IU-192.5728.98, built on July 22, 2019
Licensed to Aaron Loes
Subscription is active until October 20, 2019
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-58-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: ide.tooltip.initialDelay=399, git.explicit.commit.renames.prohibit.multiple.calls=false
Non-Bundled Plugins: Lombook Plugin, mobi.hsz.idea.gitignore, org.intellij.plugins.hcl, com.intellij.plugins.html.instantEditing, org.intellij.scala
```
 - [x] intellij-hcl plugin version (`Settings->Plugins`) `0.7.5`
 - [x] Terraform version `v0.12.6`

### Terraform Configuration Files
```hcl
data "aws_availability_zones" "available" {}

locals {
	test1  = data.aws_availability_zones.available.names[15]
	test2  = element(data.aws_availability_zones.available.names, 15)
}
```

### Exception
```text
Error: Invalid index

  on main.tf line 25, in locals:
  25: 	test1  = data.aws_availability_zones.available.names[5]
    |----------------
    | data.aws_availability_zones.available.names is list of string with 4 elements

The given key does not identify an element in this collection value.
```

### Expected Behavior
No code cleanup warning displayed

### Actual Behavior
Code cleanup warning displayed

### Steps to Reproduce
copy configuration provided and view cleanup warning in editor

**Comment by VladRassokhin** [comment]
In 0.7.7 it will no longer be highlighted as weak warning, though intention action (in Alt+Enter popup) will still be present.
