### ISSUE TITLE
ideally distinguish computed properties from others

### ISSUE THREAD

**Issue by mdaniel** [VladRassokhin/intellij-hcl#249]
### Prerequisites
 - [X] Ensure you have latest version of plugin installed
 - [X] Search for possible issue duplicates

### Installation details
 - [X] IDE version: `Build #IU-192.6262.58, built on August 20, 2019`
 - [X] intellij-hcl plugin version: `0.7.5`
 - [X] Terraform version: `Terraform v0.12.7`

### Terraform Configuration Files
```hcl
provider "random" {
  version = "~> 2.2"
}
resource "random_string" "rnd" {
  length = 1
  result = "NOPE"
}
```

### Expected Behavior
The completion dialog should understand that some properties (such as [`random_string.result`](https://github.com/VladRassokhin/terraform-metadata/blob/b78be64b7a96b01ebccaee5993b9f7e3c26f2b19/terraform/model/providers/random.json#L184)) are computed and thus should not offer it for assignment in that context, and ideally would not tolerate it appearing in a block even if the user copy-pasted it there
![image](https://user-images.githubusercontent.com/22526/63907028-b940fa00-c9ce-11e9-8b52-3c0011fbb002.png)

Failing to offer it for assignment would be a huge win, detecting it after the fact would be a nice-to-have

### Actual Behavior
```
Error: "result": this field cannot be set

  on foo.tf line 5, in resource "random_string" "rnd":
   5: resource "random_string" "rnd" {
```

### Steps to Reproduce

1. Type the name of a computed property inside a resource block
1. Invoke completion
1. Observe the computed property is offered for completion

**Comment by VladRassokhin** [comment]
Fixed, will be available in 0.7.7. Non-configurable properties won't be advised in completion. Will add inspection later.
