### ISSUE TITLE
Object properties unresolved - when defaults present

### ISSUE THREAD

**Issue by pejas** [VladRassokhin/intellij-hcl#258]
### Prerequisites
 - [x ] Ensure you have latest version of plugin installed
 - [x ] Search for possible issue duplicates

### Installation details
 - [x ] IDE version (`Help->About->Copy to Clipboard`)
IntelliJ IDEA 2019.2.1 (Ultimate Edition)
Build #IU-192.6262.58, built on August 20, 2019
 - [ x] intellij-hcl plugin version (`Settings->Plugins`)
0.7.6
 - [ x] Terraform version (`terraform -v`)
Terraform v0.12.8

### Terraform Configuration Files
```hcl
variable "my_obj" {
  type = object({
    name = string
    id = string
  })

  default = {
    id = "7"
  }
}

resource "null_resource" "test" {
  provider = var.my_obj.name
}
```

### Expected Behavior
variable var.my_obj.name is recognized as valid

### Actual Behavior
variable var.my_obj.name is highlighted as error with tool-tip: "Unresolved reference name"

### Steps to Reproduce
1. Create new tf with above content 
2. Comment/uncomment  default block to see issue
![Screenshot from 2019-09-14 22-08-37](https://user-images.githubusercontent.com/688119/64913222-83c13e00-d73c-11e9-861c-e15aa9cc1d7f.png)
![Screenshot from 2019-09-14 22-08-51](https://user-images.githubusercontent.com/688119/64913225-87ed5b80-d73c-11e9-9c43-101c7743a0f5.png)

**Comment by VladRassokhin** [comment]
Will be available in 0.7.7
