### ISSUE TITLE
Unresponsive typing when editing Terraform configuration

### ISSUE THREAD

**Issue by hhtpcd** [VladRassokhin/intellij-hcl#264]
### Prerequisites
 - [X] Ensure you have latest version of plugin installed
 - [X] Search for possible issue duplicates

### Installation details
 - [X] IDE version 
```
GoLand 2019.2.3
Build #GO-192.6817.25, built on October 2, 2019
Licensed to XXXXXX
Subscription is active until July 12, 2020
Runtime version: 11.0.4+10-b304.69 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: ide.intellij.laf.enable.animation=true, run.processes.with.pty=TRUE, ide.completion.variant.limit=500, ide.mac.allowDarkWindowDecorations=true, suggest.all.run.configurations.from.context=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: String Manipulation, com.andrewbrookins.wrap_to_column, com.arcticicestudio.nord.jetbrains, com.github.mturlo.intellij.theme.spacegray, com.herokuapp.vuesion, com.markskelton.one-dark-theme, org.intellij.plugins.hcl, izhangzhihao.rainbow.brackets, PythonCore, com.google.idea.bazel.ijwb, com.intellij.kubernetes
```

 - [X] intellij-hcl plugin version -> `0.7.6`
 - [X] Terraform version `terraform v.0.12.9`

### Terraform Configuration Files
```hcl
module "gke" {
  source = "terraform-google-modules/kubernetes-engine/google//modules/private-cluster"
  version = "~> 4.1"
  ip_range_pods = ""
  ip_range_services = ""
  name = ""
  network = ""
  project_id = ""
  region = ""
  subnetwork = ""
}

provider "google" {
  version = "~> 2.12.0"
  region  = "europe-west1"
}

provider "google-beta" {
  version = "~> 2.12.0"
  region  = "europe-west1"
}
```
### Expected Behavior
Editing text is smooth and responsive.

### Actual Behavior
Editing text is unresponsive and often pauses/freezes. Checking Goland Activity Monitor window it shows a spike in CPU for HCL plugin during pauses.

This happens when no other plugins are installed, other than the HCL plugin. Uninstalling HCL plugin restores normal text editing behaviour.

Have created a video to demonstrate

https://www.dropbox.com/s/ljru5kom9iqh4j6/goland_hcl_slow_typing_2019-10-08.mov?dl=0

### Steps to Reproduce
1. Create new project
2. Paste Terraform config from above
3. Edit config

**Comment by VladRassokhin** [comment]
Thanks for reporting, will try to fix ASAP. Will be available in 0.7..7
