### ISSUE TITLE
metadata for cloudflare got updated

### ISSUE THREAD

**Issue by boredland** [VladRassokhin/intellij-hcl#265]
### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [2019.2.3] IDE version (`Help->About->Copy to Clipboard`) 
 - [0.7.6] intellij-hcl plugin version (`Settings->Plugins`)
 - [0.12.7] Terraform version (`terraform -v`)

### Terraform Configuration Files
```hcl
// add mx records for user mail
resource "cloudflare_record" "mx" {
  for_each   = {
  for key, value in var.mx_records:
  value.target => value
  }
  zone_id    = cloudflare_zone.zone.id
  name       = each.value.prefix != "" ? each.value.prefix : cloudflare_zone.zone.zone
  type       = "MX"
  value      = each.key
  priority   = each.value.priority
  ttl        = 3600
  depends_on = [
    cloudflare_zone.zone]
}
```

### Expected Behavior
The hcl definition should pass validation.
### Actual Behavior
The syntaxhighlighting says `Missing required properties: domain" -> the metadata isn't up to date with the changes for the cloudflare provider v2.0: https://www.terraform.io/docs/providers/cloudflare/guides/version-2-upgrade.html

**Comment by VladRassokhin** [comment]
Thanks for reporting, will try to fix ASAP
