### ISSUE TITLE
How do you run `terraform fmt` in IntelliJ?

### ISSUE THREAD

**Issue by fubar** [VladRassokhin/intellij-hcl#271]
Missing instructions: How do I set up IntelliJ to run `terraform fmt`?

**Comment by VladRassokhin** [comment]
There's an action 'terraform fmt', you can invoke by searching in 'shift+shift' or 'cmd+shift+a'
Also you can run it before commit (checkbox in commit dialog)
Also 'file watcher' could be set up to run it after changes made in editor (usually on focus lose)

**Comment by fubar** [comment]
Got it, thanks.
