### ISSUE TITLE
Terraform v0.12.17 reports warning on variable type , intellij-hcl reports error on fixed code

### ISSUE THREAD

**Issue by dcfsc** [VladRassokhin/intellij-hcl#272]
### Prerequisites
 - [X ] Ensure you have latest version of plugin installed
 - [X ] Search for possible issue duplicates

### Installation details

IDE version (`Help->About->Copy to Clipboard`)
IntelliJ IDEA 2019.2.4 (Ultimate Edition)
Build #IU-192.7142.36, built on October 28, 2019
Subscription is active until June 22, 2020
Runtime version: 11.0.4+10-b304.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 3.10.0-957.27.2.el7.x86_64
GC: ParNew, ConcurrentMarkSweep
Memory: 4062M
Cores: 4
Registry: 
Non-Bundled Plugins: String Manipulation, com.jotc.nsis.plugin.nsis, com.krylysov.nsisplugin, com.oliverlockwood.plugins.jenkinsfile, io.protostuff.protostuff-jetbrains-plugin, org.asciidoctor.intellij.asciidoc, org.intellij.plugins.hcl, org.jetbrains.plugins.go-template, com.jetbrains.lang.ejs, com.jetbrains.plugins.jade, MavenRunHelper, com.intellij.plugin.adernov.powershell, org.jetbrains.plugins.go, Pythonid, com.vladsch.idea.multimarkdown, org.jetbrains.plugins.ruby, org.toml.lang

intellij-hcl plugin version: 0.7.7
Terraform v0.12.17

### Terraform Configuration Files
```hcl
variable "global_azure_portal_ip_ranges_map" {
  type    = "map"
  default = {
    "AzureOther1" = "104.42.195.92" # split to allow correct values() function call
    "AzureOther2" = "40.76.54.131"
    "AzureOther3" = "52.176.6.30"
    "AzureOther4" = "52.169.50.45"
    "AzureOther5" = "52.187.184.26"
  }
}
```

### Expected Behavior

After upgrading to new Terraform 0.2.17, a warning appeared:
```
Warning: Quoted type constraints are deprecated

  on ../../modules/global_variables/variables.tf line 20, in variable "global__staff_ip_ranges_map":
  20:   type    = "map"

Terraform 0.11 and earlier required type constraints to be given in quotes,
but that form is now deprecated and will be removed in a future version of
Terraform. To silence this warning, remove the quotes around "map" and write
map(string) instead to explicitly indicate that the map elements are strings.
```

Removing the quotes as instructed should simply remove the warning from the `apply` and leaving the quotes should show a warning indicating the syntax has changed.

### Actual Behavior

Removing the quotes shows an Inspection error in red color at the noted location:

```hcl
variable "global_azure_portal_ip_ranges_map" {
  type    = map   <<<<<< changed to remove quotes, showing an error in red color
  default = {
    "AzureOther1" = "104.42.195.92" # split to allow correct values() function call
...
  }
}
```
And the hover text shows 
```
The map type constructor requires one argument specifying the element type
```

### Steps to Reproduce

1. Remove the quotes as instructed.

**Comment by kir4h** [comment]
I actually like this warning because it forces you to be more explicit on your variables. So instead of map, declaring `map(string)` for this case or , or map(object({ field1 = string, ... } for structured types. But I agree that if `terraform` itself is not complaining, this check should be a toggle in inspection settings.

**Comment by dcfsc** [comment]
I didn't realize that adding a type made the warning go away. I do like that better, too. 

I also agree it should not be an error.

**Comment by VladRassokhin** [comment]
In 0.7.9 I'll make sure it's reported as warning, not error.
