### ISSUE TITLE
Plugin is ignoring .tf file

### ISSUE THREAD

**Issue by fniko** [VladRassokhin/intellij-hcl#278]
### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [2019.2.4] IDE version
 - [0.7.7] intellij-hcl plugin version
 - [v0.12.18] Terraform version

### Terraform Configuration Files
```hcl
#Resources
resource "digitalocean_droplet" "project-dns" {
  image = "ubuntu-18-04-x64"
  name = "project-dns"
  region = "LON1"
  size = "s-1vcpu-2gb"

  monitoring = true
  private_networking = true
  tags = ["project-dns"]
}
```

### Expected Behavior
Plugin reding the .tf and working fine

### Actual Behavior
The file named do_project_devops.tf is being ignored by the plugin (syntax highlight does not work). I see the pop up on the top saying "Plugins supporting .tf found", even though the plugin is installed already. When I rename the file, the plugin works fine.
(This file also does not have TF icon in the file tree)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Name the file do_project-devops.tf

**Comment by VladRassokhin** [comment]
Please check file type associations `Preferences -> Editor -> FIle Types` and ensure that 'Terraform Configs' have '*.tf' registered pattern.

**Comment by fniko** [comment]
Hi, yes, it has to be. Otherwise, it would not work for other files I work with.
