### ISSUE TITLE
Autocompletion does not work for complex object module outputs

### ISSUE THREAD

**Issue by jpattersonz** [VladRassokhin/intellij-hcl#279]
### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`)
```
IntelliJ IDEA 2019.2.3 (Community Edition)
Build #IC-192.6817.14, built on September 24, 2019
Runtime version: 11.0.4+10-b304.69 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: 
Non-Bundled Plugins: org.intellij.plugins.hcl, org.intellij.scala, org.jetbrains.plugins.hocon
```
 - [x] intellij-hcl plugin version (`Settings->Plugins`)
```
0.7.7
```
 - [x] Terraform version (`terraform -v`)
```
Terraform v0.12.6
```

### Terraform Configuration Files
./child/main.tf
```hcl
output "complex" {
  value = {
    top = {
      middle = {
        bottom = "nope"
      }
    }
  }
}
```
./main.tf
```hcl
module "child" {
  source = "./child"
}

output "test" {
  value = module.child.complex.top.middle.bottom
}
```
### Exception
```text
Unresolved reference top
```

### Expected Behavior
top, middle, and bottom should all resolve, as this is valid terraform code in version 0.12.*.

### Actual Behavior
top (and thus all three) don't resolve
note: `terraform validate` succeeds

### Steps to Reproduce

1. Place cursor after `value = module.child.complex`
2. Invoke completion.

**Comment by VladRassokhin** [comment]
Will be fixed in upcoming update
