### ISSUE TITLE
no code completion for cloudfront?

### ISSUE THREAD

**Issue by sdole** [VladRassokhin/intellij-hcl#28]
Hello, I am starting to use this for a project. I did not see code completion for [cloudfront](https://www.terraform.io/docs/providers/aws/r/cloudfront_distribution.html) can it be added?

**Comment by VladRassokhin** [comment]
I've updated Terraform model used in plugin. Update plugin to 0.5.3. It's available in plugin repository, just run 'Check for Updates' action in IDEA.

**Comment by sdole** [comment]
thanks!
