### ISSUE TITLE
Clarify Deprecation Notice

### ISSUE THREAD

**Issue by mousedownmike** [VladRassokhin/intellij-hcl#280]
The Deprecation notice in README.md states "This repository is no longer maintained".  However, this does appear to be the active (and only) issue tracker for issues relating to the plugin.  It might help others if that were made clear... I went through a bit of a loop trying to find where the active bug tracker was.

Thanks for the plugin and transferring it to JetBrains seems like a rational choice.

**Comment by lookfirst** [comment]
Confirmed it is the issue tracker. https://youtrack.jetbrains.com/issue/IDEA-233057

**Comment by haidaraM** [comment]
I created an issue on their issue tracker regarding the maintenance of this plugin: https://youtrack.jetbrains.com/issue/IDEA-237041

**Comment by VladRassokhin** [comment]
Thank you for suggestion, updated ReadMe.md with details about issue tracking. 
Since plugin releases separately from IntelliJ it's easier to track issues here because most of YouTrack fields (IJ Affected Version, IJ Fix Version, etc) won't apply to plugin.

**Comment by mousedownmike** [comment]
Looks good, closing this issue.
