### ISSUE TITLE
Warns for missing attribute "instance_template" on resource "google_compute_instance_group_manager"

### ISSUE THREAD

**Issue by carmelid** [VladRassokhin/intellij-hcl#283]
### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`)
> IntelliJ IDEA 2019.3.1 (Ultimate Edition)
Build #IU-193.5662.53, built on December 18, 2019
 - [x] intellij-hcl plugin version (`Settings->Plugins`)
> 0.7.7
 - [x] Terraform version (`terraform -v`)
> Terraform v0.12.19
> + provider.google v3.4.0
> + provider.google-beta v3.4.0
> ...

### Expected Behavior
No warnings should appear [as per the example](https://www.terraform.io/docs/providers/google/r/compute_instance_group_manager.html#example-usage-with-multiple-versions-google-beta-provider-)

### Actual Behavior
```text
Missing required properties: instance_template 
```
appears and highlights the section

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Copy-paste the example into IntelliJ and see the section get highlighted
```hcl
resource "google_compute_instance_group_manager" "appserver" {
  provider = google-beta
  name     = "appserver-igm"

  base_instance_name = "app"
  zone               = "us-central1-a"

  target_size = 5

  version {
    name              = "appserver"
    instance_template = google_compute_instance_template.appserver.self_link
  }

  version {
    name              = "appserver-canary"
    instance_template = google_compute_instance_template.appserver-canary.self_link
    target_size {
      fixed = 1
    }
  }
}
```

**Comment by VladRassokhin** [comment]
Fixed by schema update in 0.7.8
