### ISSUE TITLE
Missing subnet_id on azurerm_network_interface completion

### ISSUE THREAD

**Issue by tracphil** [VladRassokhin/intellij-hcl#284]
### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version: PyCharm 2019.3.1 (Professional Edition)
 - [x] intellij-hcl plugin version: 0.7.7
 - [x] Terraform version: v0.12.19

### Terraform Configuration Files
N/A

### Expected Behavior

```hcl
resource "azurerm_network_interface" "" {
  location            = ""
  name                = ""
  resource_group_name = ""
  ip_configuration {
    name                          = ""
    private_ip_address_allocation = ""
    subnet_id                     = ""
  }
}
```

### Actual Behavior
```hcl
resource "azurerm_network_interface" "" {
  location            = ""
  name                = ""
  resource_group_name = ""
  ip_configuration {
    name                          = ""
    private_ip_address_allocation = ""
  }
}
```
### Steps to Reproduce

1. Create new resource for `azurerm_network_interface`
2. Invoke completion.

**Comment by VladRassokhin** [comment]
Thats' expected behaviour. Plugin follows schema grabbed from provider sources where 'subnet_ip' marked as Optional.

Also [documentation states the same](https://www.terraform.io/docs/providers/azurerm/r/network_interface.html#subnet_id):

>subnet_id - (Optional) The ID of the Subnet where this Network Interface should be located in.
>Note: This is required when private_ip_address_version is set to IPv4.

'Note' is not in the plugin easily accessible code, so plugins doesn't know about it.
