### ISSUE TITLE
Omit Quotes In Terraform Resource Type And Name

### ISSUE THREAD

**Issue by Tensho** [VladRassokhin/intellij-hcl#285]
### Feature Request

Terraform 0.12+ allows to omit redundant quotes around resource type and name. Please could you make it configurable in "Editor –> Code Style –> Terraform Config"?

### Terraform Configuration Example
```hcl
resource aws_sns_topic opsgenie_service_health {
  name = "opsgenie-service-health"
}
```

**Comment by Tensho** [comment]
Does it make sense?

**Comment by VladRassokhin** [comment]
Makes sense, yes, will try to implement in further versions

**Comment by Tensho** [comment]
@VladRassokhin Is it still on the roadmap? 😅

**Comment by Tensho** [comment]
This is not more relevant. Here is a comment from HashiCorp representative:

> For the real reasoning, I think it has to do with whether or not the token represents a configuration language keyword or expression, which in this case it doesn’t since it is intended as a label (and can potentially have characters outside that of an expression).  I believe the allowance of non-quotes there was incidental more than intentional and the quotes being idiomatic is there for the consistency of those labels which might require the quotes.
> In the future, the SDK may support block syntax like this:
> ```
> resource "example_thing" "example" {
>   some_block "label1" {
>     # nested attributes
>   }
>   some_block "label2" {
>     # nested attributes
>   }
> }
> ```
> Which will likely have the quoting requirement for "label1" and "label2" for similar reasons.

and further [MR](https://github.com/hashicorp/terraform/pull/26390/files#diff-417e34ecb2a98ba7608882fff0a29e1c608432a49d1be1bfff302809c444441eR299) making formatter not happy with unquoted labels.

### References

- https://github.com/hashicorp/terraform/blob/v0.14/CHANGELOG.md#0140-december-02-2020
-

**Comment by Tensho** [comment]
@VladRassokhin Thank you for the patience 🙇

**Comment by VladRassokhin** [comment]
@Tensho Thank you for investigation and follow-up!
