### ISSUE TITLE
Multiple attributes for google_compute_ha_vpn_gateway marked as "unresolved reference"

### ISSUE THREAD

**Issue by metroshica** [VladRassokhin/intellij-hcl#287]
### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`)
```
PyCharm 2019.3.1 (Community Edition)
Build #PC-193.5662.61, built on December 18, 2019
Runtime version: 11.0.5+10-b520.17 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: 
Non-Bundled Plugins: aws.toolkit, org.intellij.plugins.hcl

```
 - [x] intellij-hcl plugin version (`Settings->Plugins`)
```
0.7.7
```
 - [x] Terraform version (`terraform -v`)
```
0.12.20
```
### Terraform Configuration Files
```hcl
provider "google-beta" {
  version     = "~> 3.5.0"
}

resource "google_compute_ha_vpn_gateway" "ha-vpn1" {
  provider = google-beta
  name     = "ha-vpn1"
  network  = var.gcp_network_name
}
```

### Exception
```text
For exceptions paste exception stack trace here. If it's huge one - use gist.
```

### Expected Behavior
No warnings should appear.

### Actual Behavior
vpn_interfaces highlighted red with the message: `Unresolved reference vpn_interfaces`
List of attributes affected:
- description
- project
- region
- self_link
- vpn_interfaces

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Copy and paste Terraform configuration file above to see highlighted attribute.
2. Replace highlighted attribute with attributes from list.

**Comment by VladRassokhin** [comment]
There's no 'vpn_interfaces' in sample code, though I'm sure issue is resolved by updating terraform metadata in 0.7.8
