### ISSUE TITLE
terraform scaleway_instance_ip.public_ip.address unresolved reference

### ISSUE THREAD

**Issue by lookfirst** [VladRassokhin/intellij-hcl#289]
Originally filed here:  https://youtrack.jetbrains.com/issue/IDEA-233057

### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates
 - [x] Clicked 'Reload terraform metadata model

### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`)

IntelliJ IDEA 2019.3.3 (Ultimate Edition)

 - [x] intellij-hcl plugin version (`Settings->Plugins`)

0.7.7

 - [x] Terraform version (`terraform -v`)

```
Terraform v0.12.20
+ provider.cloudflare v2.3.0
+ provider.scaleway v1.13.0
```

### Expected Behavior
No error

### Actual Behavior

![image](https://user-images.githubusercontent.com/85355/74577591-d5b4fc80-4f44-11ea-9c64-154f4701e523.png)

![image](https://user-images.githubusercontent.com/85355/74577682-4d832700-4f45-11ea-98be-04bec38cdac1.png)

### Steps to Reproduce

```
output "ip" {
  value = scaleway_instance_ip.public_ip.address
}
```

IU-193.6494.35, JRE 11.0.5+10-b520.38x64 JetBrains s.r.o, OS Mac OS X(x86_64) v10.14.6, screens 2048x1280

**Comment by VladRassokhin** [comment]
Fixed with schema update in 0.7.8
