### ISSUE TITLE
Resource existence detection not working for certain resources

### ISSUE THREAD

**Issue by fredo838** [VladRassokhin/intellij-hcl#290]
Thank you for opening an issue.
In this template paragraph text could be removed, however please retain headers.

### Prerequisites
 - [X] Ensure you have latest version of plugin installed
 - [X] Search for possible issue duplicates

### Installation details
 - [ ] IDE version (`Help->About->Copy to Clipboard`)
 - [x] intellij-hcl plugin version (`Settings->Plugins`) 0.7.7
 - [x] Terraform version (`terraform -v`) Terraform v0.12.18

### Terraform Configuration Files
```hcl
resource "google_cloud_run_service" "endpoints_service" {
  name = local.esp_name
  location = "europe-west1"
  project = var.project
  template {
    spec {
      containers {
        image = "gcr.io/endpoints-release/endpoints-runtime-serverless:2"
        /*
        env {
          name = "ENDPOINTS_SERVICE_NAME"
          value = data.external.dummy_creator.result.URL
        }
        */
      }
    }
  }
}

resource "null_resource" "debug" {
  provisioner "local-exec" {
    command = "bash -c 'echo ${google_cloud_run_service.endpoints_service.status.0.url}'"
  }
}
```
### Expected Behavior
Values are blue. 

### Actual Behavior
The values should not be marked as not detected. They are marked red, as if they don't exist, but they do exist, and `terraform apply` works fine. 

![image](https://user-images.githubusercontent.com/11276933/74860196-8574da80-5348-11ea-91ee-8e4dad47d827.png)

### Steps to Reproduce
1. Install the plugin in Pycharm IDE 
2. Install provider "google"
3. define the google provider in `provider.tf`:
```
provider "google" {
}
```
4. Create the two resources defined above in `main.tf`.
5. Look at the colour of the `.status.0.url`. Note, `.id` does get marked as blue (existing).

**Comment by VladRassokhin** [comment]
Fixed with schema update in 0.7.8
