### ISSUE TITLE
/**/ interpreted wrong when close proceed with *

### ISSUE THREAD

**Issue by c-carpenter** [VladRassokhin/intellij-hcl#294]
### Installation details
 - IDE version (`Help->About->Copy to Clipboard`)
IntelliJ IDEA 2019.3.4 (Ultimate Edition)
Build #IU-193.6911.18, built on March 17, 2020
Licensed to Christopher Carpenter
Subscription is active until April 20, 2020
Runtime version: 11.0.6+8-b520.43 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: terminal.buffer.max.lines.count=10000
Non-Bundled Plugins: Pythonid, cc.duduhuo.git-conflict, com.alayouni.ansiHighlight, com.godwin.json.parser, com.intellij.lang.puppet, intellij.prettierJS, net.sjrx.intellij.plugins.systemdunitfiles, org.intellij.plugins.hcl, org.jetbrains.plugins.ruby, org.toml.lang
 - intellij-hcl plugin version (`Settings->Plugins`)
0.7.7
 - Terraform version (`terraform -v`)
0.11.14

### Terraform Configuration Files
```hcl
/******************************************************************************

Block comment here

******************************************************************************/

terraform {
  required_version = "0.11.14"
}

```

### Exception
```text
N/A
```

### Expected Behavior
What should have happened?
Terraform code below the block comment should be highlight correctly.

This usage of /* */ does not cause problems for terraform.

### Actual Behavior
What actually happened?
When using /* */ comment block and proceeding the close with * so that you have **/, the plugin does not handle closing the comment.  

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create comment block with /* */
2. Place a * directly before the */

**Comment by VladRassokhin** [comment]
Thanks for reporting, fix will be available in next update.
