### ISSUE TITLE
EOF object not handled well

### ISSUE THREAD

**Issue by zpeterg** [VladRassokhin/intellij-hcl#30]
If an EOF block is included, such as this example from the Terraform website, everything from the <<EOF to the end of the document is white, with a red error underline at the very end. This occurs even though the Terraform code is handled just fine by Terraform. Could this be fixed?

```
provisioner "chef"  {
        attributes_json = <<EOF
        {
            "key": "value",
            "app": {
                "cluster1": {
                    "nodes": [
                        "webserver1",
                        "webserver2"
                    ]
                }
            }
        }
        EOF
        environment = "_default"
        run_list = ["cookbook::recipe"]
        node_name = "webserver1"
        secret_key = "${file("../encrypted_data_bag_secret")}"
        server_url = "https://chef.company.com/organizations/org1"
        validation_client_name = "chef-validator"
        validation_key = "${file("../chef-validator.pem")}"
        version = "12.4.1"
    }
```

Above code is from: https://www.terraform.io/docs/provisioners/chef.html

**Comment by VladRassokhin** [comment]
Seems something again changed in heredoc support in Terraform.
Previously only `<<-EOF` had support offsetted end block.
Will fix in next version.

**Comment by zpeterg** [comment]
Thank you!

**Comment by VladRassokhin** [comment]
Version 0.5.4 was uploaded to plugins repository, please try it.

**Comment by zpeterg** [comment]
Looks good! Thanks again!
