### ISSUE TITLE
Update Fastly Schema

### ISSUE THREAD

**Issue by wbautistaEXPEDIA** [VladRassokhin/intellij-hcl#301]
The `fastly_ip_ranges` data source now includes `ipv6_cidr_blocks`. The plugin does not recognize that property. I believe the provider schema needs to be updated.

### Prerequisites
 - [X] Ensure you have latest version of plugin installed
 - [X] Search for possible issue duplicates

### Installation details
 - [X] IDE version
```
IntelliJ IDEA 2019.2.3 (Ultimate Edition)
Build #IU-192.6817.14, built on September 23, 2019
Licensed to Expedia, Inc. / Billy Bautista
You have a perpetual fallback license for this version
Subscription is active until May 1, 2021
Runtime version: 11.0.4+10-b304.69 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: IdeaVIM, claims.bold.intellij.avro, org.intellij.clojure, org.intellij.plugins.hcl, Karma, org.jetbrains.kotlin, com.intellij.plugins.html.instantEditing, org.intellij.scala, org.jetbrains.plugins.go, JSTestDriver Plugin, Pythonid, org.jetbrains.plugins.ruby
```
 - [X] intellij-hcl plugin version
```0.7.9```
 - [X] Terraform version
```0.12.21```
### Terraform Configuration Files
```hcl
data "fastly_ip_ranges" "fastly_ips" {}

resource "aws_security_group" "fastly_sg" {
  name = "Fastly"
  vpc_id = var.vpc_id

  ingress {
    from_port = 443
    protocol = "tcp"
    to_port = 443
    cidr_blocks = [data.fastly_ip_ranges.fastly_ips.cidr_blocks]
    ipv6_cidr_blocks = [data.fastly_ip_ranges.fastly_ips.ipv6_cidr_blocks]
  }
}

```

### Exception
```text
N/A
```

### Expected Behavior
The IDE should display no warnings/errors.

### Actual Behavior
The IDE indicates
`Unresolved reference ipv6_cidr_blocks`

### Steps to Reproduce
1. Create a new `.tf` file.
2. Ensure fastly provider is used.
3. Copy & paste HCL from above into `.tf` file.
4. Observe inspection error.

**Comment by haidaraM** [comment]
For fast schema updates, you should consider [these instructions](https://github.com/VladRassokhin/intellij-hcl#terraform-external-metadata). If you want to have the updates more quickly, you may give a try to the fork in this [PR](https://github.com/VladRassokhin/terraform-metadata/pull/5) which is automatically updated every day.

**Comment by wbautistaEXPEDIA** [comment]
🤦 My bad. That works, thanks!
