### ISSUE TITLE
Add support for "azurerm_netapp_volume" - support the "mount_ip_addresses" property 

### ISSUE THREAD

**Issue by steve-reichert-kr** [VladRassokhin/intellij-hcl#304]
Thank you for opening an issue.
In this template paragraph text could be removed, however please retain headers.

### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`)
IntelliJ IDEA 2020.1.2 (Community Edition)
Build #IC-201.7846.76, built on June 1, 2020
Runtime version: 11.0.7+10-b765.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-37-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1964M
Cores: 4
Non-Bundled Plugins: org.jetbrains.kotlin, org.intellij.plugins.hcl
Current Desktop: MATE
 - [x] intellij-hcl plugin version (`Settings->Plugins`)
0.7.9
 - [x] Terraform version (`terraform -v`)
Terraform v0.12.26

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configuration here - for large Terraform configs,
# please use a gist (https://gist.github.com) and share a link. 
data "template_file" "init" {
  template = file("./files/cloud-init.sh")
  vars = {
    subscription_id      = var.subscription_id
    resource_group_name  = var.resource_group_name

    ansible_user_id               = var.ansible_user_id
    ansible_password              = var.ansible_password
    ansible_workflow_template_uri = var.ansible_workflow_template_uri
    ansible_inventory_uri         = var.ansible_inventory_uri
    ansible_nfs_mount_path        = format("/%s", azurerm_netapp_volume.na_volume.name)
    ansible_nfs_source            = format("%s:/%s", data.azurerm_netapp_volume.netapp-volume.mount_ip_addresses[0], azurerm_netapp_volume.na_volume.volume_path)
  }
}
```

### Expected Behavior
Plugin does not support "azurerm_netapp_volume" the "mount_ip_addresses" property 

What should have happened?
"mount_ip_address" should have been shown via auto completion and not result in a error in the terraform script.
### Actual Behavior
Use of the "mount_ip_addresses" property shows as an error and is not displayed via auto completion.

### Steps to Reproduce
Attempt to use the property in a terraform script.

**Comment by haidaraM** [comment]
Did you consider the note in the Readme: https://github.com/VladRassokhin/intellij-hcl#terraform-external-metadata about updating the metadata ? It should fix the issue

**Comment by VladRassokhin** [comment]
Updated metadata one again in 0.7.10
