### ISSUE TITLE
Support for IntelliJ 2020+

### ISSUE THREAD

**Issue by dejan-mladenovski** [VladRassokhin/intellij-hcl#305]
### Prerequisites
 - [ ] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version 
    IntelliJ IDEA 2020.1.2 (Ultimate Edition)
    Build #IU-201.7846.76, built on June 1, 2020
    Licensed to XXXXXXXXX
    Subscription is active until XXXXXXXX
    Runtime version: 11.0.7+10-b765.53 x86_64 
    VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
    macOS 10.15.5
    GC: ParNew, ConcurrentMarkSweep
     Memory: 1979M
Cores: 12
Non-Bundled Plugins: Lombook Plugin, aws.toolkit
 - [ ] intellij-hcl plugin version (`Settings->Plugins`) 
   Could not be installed, incompatible IDE version
 - [x] Terraform version (`terraform -v`) 0.12.28

### Actual Behavior
What actually happened?
Cannot install the plugin, it is not compatible with IntelliJ IDEA 2020+. Can you add a build compatible with the latest IntelliJ IDE major version?

**Comment by VladRassokhin** [comment]
Fixed in 0.7.10
