### ISSUE TITLE
Wrong "conflict with" error for "providers"/"count"

### ISSUE THREAD

**Issue by njam** [VladRassokhin/intellij-hcl#311]
When a `module` definition has both a "providers" and a "count" property, Intellij will mark that as an error, but actually the code applies just fine with Terraform 0.13.1. The same is the case for "providers" and "for_each".

### Prerequisites
 - [x] Ensure you have latest version of plugin installed: 0.7.10
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version:
```
IntelliJ IDEA 2020.2.1 (Ultimate Edition)
Build #IU-202.6948.69, built on August 24, 2020
Licensed to ...
Subscription is active until ...
Runtime version: 11.0.8+10-b944.31 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.8.4-arch1-1
GC: ParNew, ConcurrentMarkSweep
Memory: 4916M
Cores: 12
Non-Bundled Plugins: com.intellij.nativeDebug, io.protostuff.protostuff-jetbrains-plugin, name.kropp.intellij.makefile, net.seesharpsoft.intellij.plugins.csv, org.intellij.plugins.hcl, org.toml.lang, intellij.prettierJS, com.dmarcotte.handlebars, org.jetbrains.plugins.vue, org.jetbrains.kotlin, com.intellij.lang.jsgraphql, com.jetbrains.php, Pythonid, ru.meanmail.plugin.requirements, org.jetbrains.plugins.go, org.rust.lang
Current Desktop: GNOME
```
 - [x] intellij-hcl plugin version: 0.7.10
 - [x] Terraform version: v0.13.1

### Terraform Configuration Files
```hcl
terraform {
  required_version = ">= 0.13"
}

provider "aws" {
  region = "ap-east-1"
  alias = "aws1"
}

module "vpc" {
  source = "terraform-aws-modules/vpc/aws"
  cidr = "10.0.0.0/16"

  count = 3
  providers = {
    aws = aws.aws1
  }
}
```

### Expected Behavior
File syntax should be marked as 'valid'.

### Actual Behavior
File syntax has 2 'errors', specifically that the `modules`'s properties "count" and "providers" are in conflict.  
![image](https://user-images.githubusercontent.com/360800/91559414-57e09d80-e938-11ea-864a-e603c00a69bd.png)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a file `main.tf` with the contents from above
2. Run `terraform get` to download the module code
3. Wait for "problems" analysis

**Comment by VladRassokhin** [comment]
Fixed in next version

**Comment by VladRassokhin** [comment]
Finally 0.7.11 was released
