### ISSUE TITLE
Incorrect "Argument names must not be quoted" error when referencing dynamic resources

### ISSUE THREAD

**Issue by G-Rath** [VladRassokhin/intellij-hcl#312]
### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`)

<details>
IntelliJ IDEA 2020.2 (Ultimate Edition)
Build #IU-202.6397.94, built on July 27, 2020
Licensed to Gareth Jones
Subscription is active until June 22, 2021
Runtime version: 11.0.7+10-b944.20 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 3014M
Cores: 12
Registry: find.search.in.excluded.dirs=true, analyze.exceptions.on.the.fly=true, windows.jumplist=true, show.affected.tests.in.changelists=true, go.run.processes.with.pty=false, eslint.language.service.full.log=true
Non-Bundled Plugins: CMD Support, Key Promoter X, PsiViewer, com.alayouni.ansiHighlight, com.intellij.apacheConfig, com.intellij.ideolog, String Manipulation, com.jetbrains.plugins.ini4idea, com.intellij.plugins.watcher, org.intellij.plugins.postcss, org.jetbrains.plugins.slim, de.thomasrosenau.diffplugin, lermitage.intellij.battery.status, name.kropp.intellij.makefile, net.seesharpsoft.intellij.plugins.csv, net.vektah.codeglance, org.elixir_lang, org.intellij.plugins.hcl, uk.co.ben-gibson.remote.repository.mapper, mobi.hsz.idea.gitignore, org.jetbrains.plugins.vagrant, AWSCloudFormation, com.intellij.kubernetes, org.sylfra.idea.plugins.linessorter, org.toml.lang, com.intellij.plugin.adernov.powershell, com.perl5, com.deadlock.scsyntax, com.intellij.plugins.webcomponents, com.jetbrains.lang.ejs, cucumber-javascript, intellij.prettierJS, jones.restarteslintaction.restart-eslint-action, com.dmarcotte.handlebars, com.emberjs, Dart, io.flutter, org.jetbrains.plugins.node-remote-interpreter, org.jetbrains.plugins.vue, org.jetbrains.kotlin, com.intellij.plugins.html.instantEditing, com.jetbrains.plugins.jade, com.intellij.lang.jsgraphql, com.jetbrains.php, com.jetbrains.php.blade, de.espend.idea.laravel, com.jetbrains.php.drupal, com.jetbrains.php.wordPress, com.raket.silverstripe, net.king2500.plugins.PhpAdvancedAutoComplete, org.jetbrains.plugins.phpstorm-remote-interpreter, org.jetbrains.plugins.phpstorm-docker, org.jetbrains.plugins.phpstorm-wsl, com.jetbrains.twig, org.jetbrains.plugins.ruby, jones.foldcallblocks.fold-call-blocks, org.jetbrains.plugins.ruby-chef, Pythonid, aws.toolkit, ru.meanmail.plugin.requirements, org.jetbrains.plugins.go, ru.adelf.idea.dotenv
</details>

 - [x] intellij-hcl plugin version (`Settings->Plugins`) 0.7.10
 - [x] Terraform version (`terraform -v`) 0.12

### Terraform Configuration Files
```hcl
locals {
  m = {
    (aws_ec2_tag.root_volume_tags["Name"].value) = aws_ec2_tag.root_volume_tags["DLM-SnapshotGroup"].value,
  }
}
```

### Expected Behavior

No error.

### Actual Behavior
An `Argument names must not be quoted` error is shown on `"Name"`.

### Steps to Reproduce
Paste the above code into a tf file, open in editor.

**Comment by VladRassokhin** [comment]
Fixed in next plugin version
