### ISSUE TITLE
Support variables in AWS instance tag names

### ISSUE THREAD

**Issue by chrismarget** [VladRassokhin/intellij-hcl#315]
Thank you for opening an issue.
In this template paragraph text could be removed, however please retain headers.

### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

Possibly related to #303

### Installation details
 - [GoLand 2020.2.3
Build #GO-202.7319.61, built on September 16, 2020
Licensed to christopher marget
You have a perpetual fallback license for this version
Subscription is active until August 9, 2021
Runtime version: 11.0.8+10-b944.31 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: ide.completion.variant.limit=500, suggest.all.run.configurations.from.context=true, ideFeaturesTrainer.welcomeScreen.tutorialsTree=TRUE
Non-Bundled Plugins: IdeaVIM, org.intellij.plugins.hcl] IDE version (`Help->About->Copy to Clipboard`)
 - [0.7.10] intellij-hcl plugin version (`Settings->Plugins`)
 - [0.13.4] Terraform version (`terraform -v`)

### Terraform Configuration Files
```
variable "foo_tag" {
  default = "foo"
}

resource "aws_instance" "example" {
  tags = {
    terraform = true
    Name      = "example instance"
    (var.foo_tag) = "xyz"                       <- this line
  }
}
```

### Exception
Without the parenthesis the plugin is happy, but terraform complains:
```
If this expression is intended to be a reference, wrap it in parentheses. If
it's instead intended as a literal name containing periods, wrap it in quotes
to create a string literal.
```

With the parenthesis, terraform is happy, but the IDE complains:
```
'(', ',', <operator> or '}' expected, got '='
```

### Expected Behavior
HCL plugin should not mark the line as syntactically incorrect.

### Actual Behavior
HCL plugin marked the line as syntactically incorrect.

### Steps to Reproduce
Paste example code, note red underscore at `=` character

**Comment by VladRassokhin** [comment]
As workaround for now I'd recommend to write such parameters first in object.
What happens now is plugin thinks that `"example instance"(var.foo_tag)` is a method invocation.

**Comment by VladRassokhin** [comment]
Will be fixed in next plugin release

**Comment by eriksw** [comment]
@VladRassokhin Any ETA on a fix being released? This spurious syntax error (`(...) = ...` in a map) affects maybe 10% of the files I edit.

**Comment by znerd** [comment]
Note that 0.7.11 has still not been released, see: https://plugins.jetbrains.com/plugin/7808-hashicorp-terraform--hcl-language-support/versions

Also, I wonder if this is the right place to raise issues on the plugin, since JetBrains have their own YouTrack issue tracker, and that also contains issues related to the Terraform plugin; e.g.: https://youtrack.jetbrains.com/issue/IDEA-250289
