### ISSUE TITLE
[GCP] Missing ports block from container block of google_cloud_run_service resource

### ISSUE THREAD

**Issue by 1oglop1** [VladRassokhin/intellij-hcl#316]
Hi my IDE is reporting non-existing block `ports` for `google_cloud_run_service` 
however it exists here:

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service#ports

### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version `PyCharm 2020.2.3 (Professional Edition)   Build #PY-202.7660.27, built on October 6, 2020`
 - [x] intellij-hcl plugin version (`Settings->Plugins`) `0.7.10`
 - [x] Terraform version (`terraform -v`) `0.13.5`

### Terraform Configuration Files
![image](https://user-images.githubusercontent.com/7480694/98944174-f10f6100-24f0-11eb-81eb-958a5b170104.png)

### Exception
```text
Unknown block type ports 
```

### Expected Behavior
All blocks and sub-blocks should be in the whisper

### Actual Behavior
`ports` are missing

### Steps to Reproduce
1. Use this block:
```hcl
terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
      version = ">= 3.47.0"
    }
  }
  required_version = "~> 0.13.5"
}


resource google_cloud_run_service "tenant_setup" {
  project = var.project_id
  location = var.location
  name     = "${local.name}-setup"

  template {
    spec {
      service_account_name = google_service_account.terraform.name

      containers {
        image = var.tenant_provisioner_image
        
        ports {
          container_port = var.container_port
        }
      }
    }
  }
}
```
2. Hover over `ports`and inspect the false positive

**Comment by VladRassokhin** [comment]
Fixed in 0.7.12
