### ISSUE TITLE
Terraform fmt in commit dialog should ignore .terraform.lock.hcl

### ISSUE THREAD

**Issue by chludwig-haufe** [VladRassokhin/intellij-hcl#321]
### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`)
    PyCharm 2020.3 (Professional Edition)
    Build #PY-203.5981.165, built on December 14, 2020
 - [x] intellij-hcl plugin version (`Settings->Plugins`)
    0.7.10
 - [x] Terraform version (`terraform -v`)
    0.14.2

### Steps to Reproduce
1. Following the upgrade to Terraform 0.14.x, run `terraform init`.
2. Add the created file `.terraform.lock.hcl` to your git index.
3. Commit the workspace via the PyCharm commit dialog with the "Before Commit" option `Terraform fmt` checked.

### Expected Behavior
`.terraform.lock.hcl` is commited unmodified.

### Actual Behavior
`terraform fmt` fails with the message:
```text
Error: Only .tf and .tfvars files can be processed with terraform fmt
```

**Comment by VladRassokhin** [comment]
Fixed in 0.7.13
