### ISSUE TITLE
`Unresolved reference arn` for `arn` member in `aws_codeartifact_domain` and `aws_codeartifact_repository` objects

### ISSUE THREAD

**Issue by ivancho1707** [VladRassokhin/intellij-hcl#322]
### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`)
```
WebStorm 2020.3.2
Build #WS-203.7148.54, built on January 25, 2021
Runtime version: 11.0.9.1+11-b1145.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1953M
Cores: 8
Registry: ide.intellij.laf.enable.animation=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: com.mallowigi.idea, org.intellij.plugins.hcl
```
 - [x] intellij-hcl plugin version (`Settings->Plugins`)
```
HashiCorp Terraform / HCL language Support
0.7.10
```
 - [x] Terraform version (`terraform -v`)
```
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/aws v3.25.0
```

### Terraform Configuration Files
```hcl
# Make a codeartifact domain and attach a repository to it
resource "aws_codeartifact_domain" "a_certain_code_domain" {
  domain         = "a-certain-code-domain"
}

resource "aws_codeartifact_repository" "a_certain_code_repository" {
  repository = "a-certain-code-repository"
  domain     = aws_codeartifact_domain.a_certain_code_domain.domain
}

# Now try to use the arn of the above generated resources, for instance for a iam policy
resource "aws_iam_policy" "a_certain_attached_policy" {
  name        = "CodeBuildBasePolicyForACertainModule"
  policy = jsonencode(
  {
    Version: "2012-10-17",
    Statement: [
      {
        Effect: "Allow",
        Action: [
           "codeartifact:GetAuthorizationToken",
           "codeartifact:GetRepositoryEndpoint",
        ]
        Resource: [
           aws_codeartifact_domain.a_certain_code_domain.arn,   # [!] Unresolved reference arn 
           aws_codeartifact_repository.a_certain_code_repository.arn  # [!] Unresolved reference arn 
        ]
     }
   ]
 })
}
```

### Exception
```text
None
```

### Expected Behavior
* What should have happened?
`aws_codeartifact_domain` and `aws_codeartifact_repository` objects provide correctly their members information for correct code highlighting

### Actual Behavior
What actually happened?
HCL language support plugin prompts an error `Unresolved reference arn` for `arn` member in `aws_codeartifact_domain` and `aws_codeartifact_repository` objects even when the configuration is totally valid

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Setup a new project with the above terraform configuration
2. Check code static analysis from HCL language support plugin, 2 errors prompted

**Comment by DanielRadej** [comment]
I have the same problem.

**Comment by mush20** [comment]
+1

**Comment by vinujan59** [comment]
+1

**Comment by VladRassokhin** [comment]
Fixed in 0.7.11

**Comment by isleshocky77** [comment]
@VladRassokhin Is this code committed somewhere and are the changelogs of the different releases documented somewhere?

**Comment by VladRassokhin** [comment]
@isleshocky77 plugin source code is closed, though [terraform-metadata](https://github.com/VladRassokhin/terraform-metadata) is open source. Changelog is available in "What's new" section on [plugin page](https://plugins.jetbrains.com/plugin/7808-terraform-and-hcl)

**Comment by isleshocky77** [comment]
@VladRassokhin Thanks.
