### ISSUE TITLE
Plugin does not support `instance_refresh` in `aws_autoscaling_group`

### ISSUE THREAD

**Issue by mtslzr** [VladRassokhin/intellij-hcl#326]
### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`)
 - [x] intellij-hcl plugin version (`Settings->Plugins`)
 - [x] Terraform version (`terraform -v`)

```
PhpStorm 2020.3.2 RC
Build #PS-203.7148.74, built on January 27, 2021
Licensed to Matthew Salazar
You have a perpetual fallback license for this version.
Subscription is active until December 15, 2021.
Runtime version: 11.0.9.1+11-b1145.77 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.2.1
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: com.arcticicestudio.nord.jetbrains, com.mallowigi, org.intellij.plugins.hcl, com.jetbrains.codeWithMe, name.kropp.intellij.makefile, de.espend.idea.laravel, ru.adelf.idea.dotenv

Hashicorp Terraform / HCL language support 0.7.10

Terraform v0.14.6
```

### Exception
```text
Unknown block type instance_refresh
```

![instance_refresh](https://user-images.githubusercontent.com/6003715/108374860-67e28700-71cf-11eb-99bc-fbc911137c18.png)

This property was added in 0.3.22 of the AWS provider, back in December.

Release info here: https://github.com/hashicorp/terraform-provider-aws/blob/v3.22.0/CHANGELOG.md.

Documentation of instance_refresh here: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#instance_refresh

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a block for `aws_autoscaling_group`.
2. Add a block inside that for `instance_refresh`.
3. See the warning.
4. Run `terraform apply` and see it works as intended.

**Comment by VladRassokhin** [comment]
Fixed in 0.7.11
