### ISSUE TITLE
kubernetes_pod_security_policy not recognized as valid resource

### ISSUE THREAD

**Issue by albuch** [VladRassokhin/intellij-hcl#328]
Thank you for opening an issue.
In this template paragraph text could be removed, however please retain headers.

### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`): IntelliJ IDEA 2020.3.2 (Ultimate Edition), Build #IU-203.7148.57, built on January 26, 2021
 - [x] intellij-hcl plugin version (`Settings->Plugins`): `0.7.10`
 - [x] Terraform version (`terraform -v`): `0.14.5`: 

### Terraform Configuration Files
```hcl
terraform {
  required_version = "~> 0.14"
  required_providers {
    kubernetes = {
      version = "~> 2.0"
      source = "hashicorp/kubernetes"
    }
  }
}

provider "kubernetes" {
  config_path    = "~/.kube/config"
}

resource "kubernetes_pod_security_policy" "test" {
  metadata {
    name = "test"
    annotations =  {
      "apparmor.security.beta.kubernetes.io/allowedProfileNames" : "unconfined"
    }
  }
  spec {
    privileged = false
    allow_privilege_escalation = false
    read_only_root_filesystem = true
    host_network = true
    host_pid = true

    allowed_host_paths {
      path_prefix = "/dev/log"
    }
  }
}
```

### Exception
N/A

### Expected Behavior
Intellij IDEA should recognize the ressource `kubernetes_pod_security_policy` and its blocks and attributes and supply code assit values.

### Actual Behavior
Intellij IDEA shows warnings for all blocks: Unknown block type spec. 
Intellij IDEA doesn't show `kubernetes_pod_security_policy` on code assist for ressources.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Open the HCL in Intellij IDEA
2. See warnings for resource `kubernetes_pod_security_policy`
3. create a new resource block and open code assists for resource type  (
4. Verify that `kubernetes_pod_security_policy` is not in the list of resources

**Comment by VladRassokhin** [comment]
Fixed in 0.7.11
