### ISSUE TITLE
Missing resource `aws_cloudwatch_event_bus`

### ISSUE THREAD

**Issue by mboudreau** [VladRassokhin/intellij-hcl#331]
Thank you for opening an issue.
In this template paragraph text could be removed, however please retain headers.

### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 IDE version (`Help->About->Copy to Clipboard`)
 ```
WebStorm 2021.1
Build #WS-211.6693.108, built on April 6, 2021
Licensed to Michel Boudreau
Subscription is active until January 12, 2022.
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.8.0-7642-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1877M
Cores: 8
Non-Bundled Plugins: DBN (3.2.3024.0), Statistic (4.1.7), com.github.leomillon.uuidgenerator (4.3.2), org.intellij.plugins.hcl (0.7.10), com.intellij.lang.jsgraphql (2.9.1)
Current Desktop: pop:GNOME
```
intellij-hcl plugin version (`Settings->Plugins`)
`0.7.10`
Terraform version 
`v0.14.9`

### Terraform Configuration Files
```hcl
resource "aws_cloudwatch_event_bus" "demo" {
  name = "demo"
}

resource "aws_cloudwatch_event_archive" "demo" {
  name             = "demo-archive"
  event_source_arn = aws_cloudwatch_event_bus.demo.arn  // Errors on reference .arn
  retention_days   = 14
}
```

### Exception
```text
Unresolved reference arn
```

### Expected Behavior
Should understand what `aws_cloudwatch_event_bus` resource is.

### Actual Behavior
Doesn't recognize `aws_cloudwatch_event_bus`

### Steps to Reproduce
copy-paste code above into .tf file and see error.

**Comment by VladRassokhin** [comment]
Fixed in 0.7.11
