### ISSUE TITLE
terraform plugin requires wrong attribute for VPC based transfer server

### ISSUE THREAD

**Issue by xsnrg** [VladRassokhin/intellij-hcl#336]
### Installation details
IntelliJ IDEA 2021.1.1 (Community Edition)
Build #IC-211.7142.45, built on April 30, 2021
Runtime version: 11.0.10+9-b1341.41 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.11.19-200.fc33.x86_64
GC: ParNew, ConcurrentMarkSweep
Memory: 1927M
Cores: 16
Non-Bundled Plugins: com.carbonblack.intellij.rpmspec (1.2.0), org.intellij.plugins.hcl (0.7.10), org.jetbrains.kotlin (211-1.5.0-release-759-IJ6693.72), PythonCore (211.7142.45)
Kotlin: 211-1.5.0-release-759-IJ6693.72
Current Desktop: GNOME

Terraform v0.15.1

### Terraform Configuration Files
```
resource "aws_transfer_server" "name" {
 endpoint_type = "VPC"
 identity_provider_type = "SERVICE_MANAGED"
 endpoint_details {}
```

### Expected Behavior
The plugin should not require `vpc_endpoint_id` inside of `endpoint_details`

### Actual Behavior
The plugin expects `vpc_endpoint_id` to be inside of endpoint_details{}, but that was used for the depricated VPC_ENDPOINT type.

https://docs.aws.amazon.com/transfer/latest/userguide/API_EndpointDetails.html

**Comment by VladRassokhin** [comment]
Fixed in 0.7.11
