### ISSUE TITLE
Rename of module corrupts source references

### ISSUE THREAD

**Issue by snstanton** [VladRassokhin/intellij-hcl#337]
### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`)
PyCharm 2021.1.1 (Professional Edition)
Build #PY-211.7142.13, built on April 21, 2021
Runtime version: 11.0.10+9-b1341.41 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: G1 Young Generation, G1 Old Generation
Memory: 1024M
Cores: 16
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: String Manipulation (8.15.203.000.3), org.intellij.plugins.hcl (0.7.10), org.jetbrains.plugins.go-template (211.6693.44), com.failfast (2.0.4), mobi.hsz.idea.gitignore (4.1.0), name.kropp.intellij.makefile (211.6693.108), com.intellij.kubernetes (211.7142.13), org.sylfra.idea.plugins.linessorter (1.0.1), JSTestDriver Plugin (202.5), net.ashald.envfile (3.2.1), ru.meanmail.plugin.requirements (2021.4-211)

 - [x] intellij-hcl plugin version (`Settings->Plugins`)
 0.7.10
 - [x] Terraform version (`terraform -v`)
 0.15.4

### Terraform Configuration Files
./sub1/root.tf
```hcl
terraform {}
module "foo" {
  source = "../sub2"
}
```
./sub2/main.tf
```hcl
```

### Expected Behavior
Use the "Rename" refactoring command to rename the dir "sub2" to "sub3".
The directory should be renamed and the source reference should be updated to `"../sub3"`

### Actual Behavior

The directory was renamed to sub3, but the source reference was updated to `"..\/sub3"`

### Steps to Reproduce
* Create the two files above (sub2/main.tf can be empty)
* Select the dir sub2
* Use "Refactor > Rename" to rename sub2 to sub3

The same thing happens if you select rename from the refactor menu while on the source string.

**Comment by VladRassokhin** [comment]
Fixed in 0.7.13
