### ISSUE TITLE
Support optional keyword and other terraform 1.0 language enhancements

### ISSUE THREAD

**Issue by samart** [VladRassokhin/intellij-hcl#338]
Support optional keyword for variables.
recognize tomap and tolist functions

**Comment by VladRassokhin** [comment]
What is "optional keyword for variables"? 
`tomap` and `tolist` supported in 0.7.11

**Comment by haidaraM** [comment]
`optional` experimental keyword is defined here: https://www.terraform.io/docs/language/expressions/type-constraints.html#experimental-optional-object-type-attributes.

There is also a `defaults` experimental function: https://www.terraform.io/docs/language/functions/defaults.html. Not sure if it's supported or not

**Comment by VladRassokhin** [comment]
Fixed `optional` in 0.7.14
`defaults` is somehow works.

**Comment by mrlexor** [comment]
Hello,

I've found out this closed issue regarding `optional` modifier. It's actually work, but not as expected.

`Optional` modifier has two arguments and if I use it only with as shown one, so linter shows that okay:
<img width="298" alt="Screenshot 2022-10-18 at 14 53 53" src="https://user-images.githubusercontent.com/32645155/196410824-656c5fab-59d7-4c50-8f48-52ecd5793478.png">

However, when I add the second one, `default` argument, linter, seems, doesn't know about it:
<img width="875" alt="Screenshot 2022-10-18 at 14 58 04" src="https://user-images.githubusercontent.com/32645155/196411665-f4c27bf9-b92a-46cc-9cc7-75b79a9368ad.png">

Can you take a look, please?

[Here](https://www.terraform.io/language/expressions/type-constraints#optional-object-type-attributes) you may find information about `default` argument for the `optional` modifier.
