### ISSUE TITLE
data.aws_iam_policy looked up by name is flagged as an error

### ISSUE THREAD

**Issue by snstanton** [VladRassokhin/intellij-hcl#339]
Thank you for opening an issue.
In this template paragraph text could be removed, however please retain headers.

### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version (`Help->About->Copy to Clipboard`)  
 PyCharm 2021.1.2 (Professional Edition)
Build #PY-211.7442.45, built on June 1, 2021
 - [x] intellij-hcl plugin version (`Settings->Plugins`)  
 0.7.10
 - [x] Terraform version (`terraform -v`)
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/carlpett/sops v0.6.3
+ provider registry.terraform.io/hashicorp/aws v3.45.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.2
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/terraform-aws-modules/http v2.4.1

### Terraform Configuration Files
```hcl
data "aws_iam_policy" "mypolicy" { name = "mypolicy" }
```

### Expected Behavior
This is legal syntax for the data object aws_iam_policy.
### Actual Behavior
It is flagged as missing a required "arn" argument.  Only one of "name" or "arn" is required.

### Steps to Reproduce
Load the above file into a .tf editor window and notice the data block is flagged.

**Comment by VladRassokhin** [comment]
Fixed in 0.7.11
