### ISSUE TITLE
Interpolation escape not supported

### ISSUE THREAD

**Issue by sjungwirth** [VladRassokhin/intellij-hcl#34]
Please add support for escaping interpolation syntax:

> You can escape interpolation with double dollar signs: $${foo} will be rendered as a literal ${foo} [[1]](https://www.terraform.io/docs/configuration/interpolation.html)

Example use case:
`"Resource": "arn:aws:s3:::mybucket/$${cognito-identity.amazonaws.com:sub}/*"`

**Comment by VladRassokhin** [comment]
Would be available in next plugin release

**Comment by sjungwirth** [comment]
Awesome! Thank you

**Comment by VladRassokhin** [comment]
Version 0.5.4 was uploaded to plugins repository, please try it.

**Comment by sjungwirth** [comment]
works like a charm! Thanks again
