### ISSUE TITLE
Escaped Quotes break highlight/inspection

### ISSUE THREAD

**Issue by EntilZha** [VladRassokhin/intellij-hcl#35]
Looks like if I have something like this, it will mark it as an error:

```
provisioner "remote-exec" {
    inline = ["echo \"export CONF=${var.value}\" >> /home/ubuntu/.bashrc"]
  }
```

The backslashes cause the error

**Comment by VladRassokhin** [comment]
Seems it's duplicate of #34 or fixed within that issue.
