### ISSUE TITLE
aws_cloudfront_distribution - forwarded_values validation needs to account for the cache_policy_id value

### ISSUE THREAD

**Issue by omriKaltura** [VladRassokhin/intellij-hcl#350]
### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version (`IntelliJ IDEA 2021.1.3 (Ultimate Edition)
Build #IU-211.7628.21, built on June 30, 2021`)
 - [x] intellij-hcl plugin version (`0.7.10`)
 - [x] Terraform version (`0.13.5`)

### Terraform Configuration Files
```hcl
resource "aws_cloudfront_distribution" "example" {
  ...
  default_cache_behavior {
    allowed_methods  = ["GET","HEAD"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = "anS3Bucket"
    cache_policy_id = data.aws_cloudfront_cache_policy.CachingOptimized.id
    
    viewer_protocol_policy = "redirect-to-https"
  }
  ...
}
```

### Exception
```Missing required properties: forwarded_values```

### Expected Behavior
when cache_policy_id field is configured under the default_cache_behavior, the forwarded_values block is not required by AWS
### Actual Behavior
a warning is shown on the IDE
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. add cache_policy_id without the forwarded_values block

**Comment by VladRassokhin** [comment]
Fixed in 0.7.12
