### ISSUE TITLE
Conflicting count and providers in module implementation

### ISSUE THREAD

**Issue by antonstamenov** [VladRassokhin/intellij-hcl#353]
Thank you for opening an issue.
In this template paragraph text could be removed, however, please retain headers.

### Prerequisites
 - [X] Ensure you have the latest version of the plugin installed
 - [X] Search for possible issue duplicates

### Installation details
 - [X] IDE version (`Help->About->Copy to Clipboard`)
```
PyCharm 2021.2 (Professional Edition)
Build #PY-212.4746.96, built on July 27, 2021
Licensed to XXXXX 
Subscription is active until November 26, 2021.
Runtime version: 11.0.11+9-b1504.13 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.5.2
...
```
 - [ ] intellij-hcl plugin version (`Settings->Plugins`)
`0.7.10`
 - [ ] Terraform version (`terraform -v`)
 `1.0.5`

### Terraform Configuration Files
```hcl
module "dummy" {
  count  = local.create_vpc ? 1 : 0
  source = "./"
  providers = {
    aws = aws.shd
  }
}
```

### Exception
```text
The code is highlighted as an error, while it is deployable and works ok.
```
<img width="280" alt="Screenshot 2021-09-02 at 16 31 31" src="https://user-images.githubusercontent.com/48581776/131852678-0bc42020-b84b-4a70-8b05-30b9757e7769.png">

### Expected Behavior
Accept both count and providers. Seems like they work. 

There is this text in the [documentation](https://www.terraform.io/docs/language/modules/develop/providers.html#legacy-shared-modules-with-provider-configurations), but it is about providers defined into the modules, not the ones that are defined in the callee.

```
A module containing its own provider configurations is not compatible with the for_each, count, and depends_on arguments that were introduced in Terraform v0.13. For more information, see Legacy Shared Modules with Provider Configurations.
```

### Actual Behavior
There is an error indication about conflicting properties.

### Steps to Reproduce
Paste the above code in a file in an empty folder and open it with the IDE.

**Comment by VladRassokhin** [comment]
Duplicates #311.
