### ISSUE TITLE
IDE requires optional resource property (warning is shown)

### ISSUE THREAD

**Issue by bashovski** [VladRassokhin/intellij-hcl#354]
### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version **PhpStorm 2020.1 Build #PS-201.6668.153, built on April 13, 2020**
 - [x] intellij-hcl plugin version **0.7.10**
 - [x] Terraform version: **1.0.6.**

### Terraform Configuration Files
```hcl
resource "aws_iam_role" "lambda_iam" {
  name               = "lambda_iam"
  assume_role_policy = file("./policies/lambda_iam.json")
}

resource "aws_lambda_function" "this" {
  function_name = "<name>"
  package_type  = "Image"
  image_uri     = "<id>.dkr.ecr.eu-central-1.amazonaws.com/<repo-name>:latest"
  role          = aws_iam_role.lambda_iam.arn
}

```

### Exception
/

### Expected Behavior
- ```handler``` and ```runtime``` aren't mandatory if the ```package_type``` is "Image".
- The warning shouldn't be shown.

### Actual Behavior
- Plugin detected missing properties (handler, runtime) even with present ```package_type="Image"``` 
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function#package_type

### Steps to Reproduce
![image](https://user-images.githubusercontent.com/48890281/132111547-3c394a32-8ab3-4c92-8adb-edc704d040c3.png)

**Comment by VladRassokhin** [comment]
Please update the plugin to 0.7.13

**Comment by VladRassokhin** [comment]
New plugin versions support:
0.7.11 — IDE 2020.3 and newer;
0.7.12+ — IDE 2021.1 and newer;
0.7.10 is outdated.

**Comment by VladRassokhin** [comment]
Yet you can try newest metadata, see readme at https://github.com/vladrassokhin/terraform-metadata
