### ISSUE TITLE
Support for Terraform 0.7.0 data sources

### ISSUE THREAD

**Issue by shorn** [VladRassokhin/intellij-hcl#36]
I know it's brand new, just thought I'd raise an issue for the new data sources feature: https://www.terraform.io/upgrade-guides/0-7.html

![image](https://cloud.githubusercontent.com/assets/216456/17356782/ade449d2-599c-11e6-8840-8e7f67aa467d.png)

P.S.  This plugin is great, keep up the good work.

**Comment by VladRassokhin** [comment]
Implemented would be available in next plugin release (0.5.5). Hopefully it would be released this week.

**Comment by VladRassokhin** [comment]
I've just released plugin version 0.5.0, check it out via regular 'Check for Updates' action in your IDE.

**Comment by shorn** [comment]
Works for me.  
Thanks.
