### ISSUE TITLE
Unresolved references using M1 Mac

### ISSUE THREAD

**Issue by mousedownmike** [VladRassokhin/intellij-hcl#361]
### Prerequisites
 - [X] Ensure you have latest version of plugin installed
 - [X] Search for possible issue duplicates

####  IDE version (`Help->About->Copy to Clipboard`)
```
IntelliJ IDEA 2021.2.3 (Ultimate Edition)
Build #IU-212.5457.46, built on October 12, 2021
Subscription is active until June 23, 2022.
Runtime version: 11.0.12+7-b1504.40 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6
GC: G1 Young Generation, G1 Old Generation
Memory: 1024M
Cores: 8
Registry: dart.projects.without.pubspec=true
Non-Bundled Plugins: com.intellij.plugins.watcher (212.4746.52), Statistic (4.1.7), org.intellij.plugins.hcl (0.7.10), org.asciidoctor.intellij.asciidoc (0.35.8), com.dmarcotte.handlebars (212.4746.57), aws.toolkit (1.31-212), Dart (212.4746.57), io.flutter (59.0.4), com.intellij.plugins.html.instantEditing (212.4746.57), intellij.prettierJS (212.4746.57), de.timo_reymann.intellij-mjml-support (1.19.1)
Kotlin: 212-1.5.10-release-IJ5457.46
```

 #### intellij-hcl plugin version (`Settings->Plugins`)
`0.7.14`

#### Terraform version (`terraform -v`)
```
Terraform v1.0.6
on darwin_arm64
```

### Terraform Configuration Files

This is not specific to any configuration.  I could provide mine privately but it seems to affect any configuration with minimal complexity.

### Exception
```text
None
```

### Expected Behavior
The plugin should resolve resource references.

### Actual Behavior
Many/most resource references are highlighted in red with the message `Unresolved reference reference_name`

References span the gamut from direct references, `for_each` references and `data` references.  Not all references have the issue but I cannot decipher a pattern.

### Steps to Reproduce
1. On a Linux JetBrains IDE (not M1 arm) Load a TF configuration with multiple resource references.
2. Observe resources properly resolved.
3. Open the SAME TF configuration on a M1 Mac (Macbook Air is where I found this).
4. Observe many resources flagged red with `Unresolved reference` errors.
5. `terraform plan` the configuration
6. Observe the plan succeeds (i.e. no actual errors)

**Comment by VladRassokhin** [comment]
Seems you've outdated plugin, IDE version info states `org.intellij.plugins.hcl (0.7.10)`

**Comment by mousedownmike** [comment]
@VladRassokhin I'm guessing I was reading the "Marketplace" version when I put it in there.  It appears my plugin updates were getting blocked by the need to confirm some sort of "third-party" data agreement. I've updated, and now things are working.  Thanks for the response!  Closing.
