### ISSUE TITLE
aws kinesis stream_mode_details is not recognized

### ISSUE THREAD

**Issue by Raffaello** [VladRassokhin/intellij-hcl#371]
Thank you for opening an issue.
In this template paragraph text could be removed, however please retain headers.

### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version
 ```
 IntelliJ IDEA 2021.3.1 (Community Edition)
Build #IC-213.6461.79, built on December 28, 2021
Runtime version: 11.0.13+7-b1751.21 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.11-200.fc35.x86_64
GC: G1 Young Generation, G1 Old Generation
Memory: 512M
Cores: 4
Non-Bundled Plugins:
    org.intellij.plugins.hcl (0.7.14)

 ```
 
 - [x] intellij-hcl plugin version (0.7.14)
 - [x] Terraform version (`terraform -v`)

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configuration here - for large Terraform configs,
# please use a gist (https://gist.github.com) and share a link. 
```

### Exception
```text
For exceptions paste exception stack trace here. If it's huge one - use gist.
```

### Expected Behavior
What should have happened?
it should recognize the `stream_mode_details` in the aws kinesis stream resource

### Actual Behavior
What actually happened?
highlight as unknown block.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
just do this example:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_stream

**Comment by VladRassokhin** [comment]
Fixed in 0.7.15 by metadata update
