### ISSUE TITLE
kubernetes_ingress_v1 not supported

### ISSUE THREAD

**Issue by markusheiden** [VladRassokhin/intellij-hcl#376]
### Prerequisites
 - [x] Ensure you have latest version of plugin installed
 - [x] Search for possible issue duplicates

### Installation details
 - [x] IDE version: IntelliJ IDEA 2021.3.2 RC
 - [x] intellij-hcl plugin version 0.7.14
 - [x] Terraform version 1.1.4, Kubernetes Provider 2.7.1

### Terraform Configuration Files
```hcl
resource "kubernetes_ingress_v1" "ingress" {
 ...
}
```

### Expected Behavior
Autocomplete support for the resource "kubernetes_ingress_v1" and inside the resource block ("metadata" etc.).

### Actual Behavior
"kubernetes_ingress_v1" seems to be not known to the IDE / the plugin.

### Steps to Reproduce
Create a terraform file with a "kubernetes_ingress_v1" resource. Try to autocomplete -> Does not work.

**Comment by kriswuollett** [comment]
It is not just `kubernetes_ingress_v1`. All supported [versioned resource names](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/guides/versioned-resources) seem to not be supported.

**Comment by VladRassokhin** [comment]
Fixed in 0.7.15

**Comment by markusheiden** [comment]
Thanks a lot for fixing this that fast!
