### ISSUE TITLE
Support for terraform 0.7.0 map data type overrides in .tfvars

### ISSUE THREAD

**Issue by zknill** [VladRassokhin/intellij-hcl#39]
Terraform 0.7.0 brought better support for map data types and a changed syntax for overriding the defaults/providing values in .tfvars files. The new syntax appears not to be supported by this plugin.

Example map:

```
variable "myMap" {
  type = "map"
  default = {
    foo = "bar"
    hello = "world"
  }
}
```

Old syntax for providing values from .tfvars file:
`myMap.foo = "banana"`

New syntax (as of terraform 0.7.0) for providing values from .tfvars files:

```
myMap = {
  foo = "banana"
}
```

The plugin currently highlights the new syntax as erroneous and reports:

Property value should be either number or double quoted string in .tfvars files less... (⌘F1) 
The vars file should be in the format of `key = \"value\"`

**Comment by VladRassokhin** [comment]
Thank you for reporting, as workaround you could disable that inspection: `Preferences | Editor | Inspections | Terraform Configs | Unsupported syntax` or via `Alt+Enter` intention.

**Comment by zknill** [comment]
Thanks, will do.
