### ISSUE TITLE
Auto-create closing quotes

### ISSUE THREAD

**Issue by mkuzmin** [VladRassokhin/intellij-hcl#4]
When I type opening quotation sign (`"` or `'`), editor usually adds a second closing sign automatically.
Please enable this mode for HCL.

**Comment by VladRassokhin** [comment]
Fixed in 0.2.1

**Comment by mkuzmin** [comment]
It works, but TF interpolation seems broken

**Comment by VladRassokhin** [comment]
Yes, fixed only for HCL, will search for solutions how to add `}` after `${` in string literals. 
And will also add `()` support in interpolation.

**Comment by VladRassokhin** [comment]
Should be fixed now.

**Comment by mkuzmin** [comment]
I have the same issue using version 0.4.2.

**Comment by VladRassokhin** [comment]
@mkuzmin please provide simple example.
