### ISSUE TITLE
Improve .tfvars support

### ISSUE THREAD

**Issue by VladRassokhin** [VladRassokhin/intellij-hcl#41]
- [x] Add variables names completion
- [x] Add mapped variables sub-names completion
- [x] Report incorrect variable override type: list variable overridden as map and so on
- [x] Unknown variable overridden inspection
- [x] Add variables names references resolving
- [x] Add mapped variables sub-names references resolving

**Comment by kglee79** [comment]
Would it be possible to also add support for native lists defined in tfvars as well?

mylist = ["a", "b", "c", "d"]

**Comment by VladRassokhin** [comment]
@kglee79 It's already done in #39, would be available in next update.

**Comment by VladRassokhin** [comment]
Fixed in 0.5.6 (just released)
