### ISSUE TITLE
Add support for Data Sources

### ISSUE THREAD

**Issue by tylermauthe** [VladRassokhin/intellij-hcl#46]
As of Terraform 0.7, Data Sources like `template_file` should now be declared as `data` instead of `resource`.

Currently, this plugin shows this as an error "Unknown block type data".

Would be awesome to get this updated, I am happy to help if someone can point me in the right direction! Thanks.

**Comment by VladRassokhin** [comment]
It's already done in version 0.5.5 (#36) 
Ensure you have latest version of plugin.
And what version of terraform do you use?

**Comment by tylermauthe** [comment]
Terraform version 0.7.4 -- but I'm on plugin version 0.5.3!

Sorry, I installed it from within IntelliJ by going to Browse Repositories. Will update, thanks.

**Comment by VladRassokhin** [comment]
IDEA should have advised you to update plugin. If not - run 'Check For Updates' action, it would download info about new plugins and will ask for update them.

**Comment by tylermauthe** [comment]
I'm on a crusty old version apparently and no licenses for newer -- so I'm stuck with this for now. 

Thanks though! Great plugin.
