### ISSUE TITLE
Support `cloudwatch_logging_options` for AWS Firehose delivery streams

### ISSUE THREAD

**Issue by ccampo133** [VladRassokhin/intellij-hcl#49]
Hello. With Terraform 0.7.5 there is a new configuration block for AWS Firehose delivery streams called `cloudwatch_logging_options` (see: https://www.terraform.io/docs/providers/aws/r/kinesis_firehose_delivery_stream.html#cloudwatch_logging_options). I'm simply requesting support for this in the HCL. Thanks!

**Comment by VladRassokhin** [comment]
Hi @ccampo133, 
I've just uploaded new version to plugin repository, update plugin via 'Check for Updates' action in IDEA.

**Comment by ccampo133** [comment]
Thanks. Great work on the plugin btw - I use it every day.
