### ISSUE TITLE
Highlight matching bracket signs

### ISSUE THREAD

**Issue by mkuzmin** [VladRassokhin/intellij-hcl#5]
In other languages when I point a cursor to beginning of a block, an end of the block is highlighted:
![image](https://cloud.githubusercontent.com/assets/712402/8167405/c5820b02-13a6-11e5-8371-541dbf37f112.png)

Would be nice to have it enabled in HCL.

**Comment by VladRassokhin** [comment]
Fixed in 0.2.1
