### ISSUE TITLE
Support refactoring "Extract variable"

### ISSUE THREAD

**Issue by ringods** [VladRassokhin/intellij-hcl#50]
In Intellij, for languages like Java, you have refactoring support. This might become very handy in the HCL plugin too to support Terraform refactorings.

The first refactoring I would like to see supported is to replace a constant value with a variable, given the constant value as a `default` value.

On top of that, the existence of a file `variables.tf` seems to be best practice although it is not necessarily needed. But if we follow best practices, the refactoring "Extract variable" should put the variable in the `variables.tf` file and create this file when it doesn't exist yet.

**Comment by VladRassokhin** [comment]
@ringods Could you please provides some sample configs with before/after state?

**Comment by ringods** [comment]
@VladRassokhin Sorry for the delay, but I've been overloaded with work. I'm definitely willing to do this, but wouldn't want my investment in time to be wasted after you implement this. So my proposal is to write it as a documentation on the wiki of this repo.

https://help.github.com/articles/adding-and-editing-wiki-pages-locally/

This article explains that the wiki is a separate Git repo itself. If you grant me access to the main repo, I'm also granted to clone the git repo of the Wiki. I will then put this documentation on a branch. Since it is on a branch, it is not made public as the article explains. Once the implementation is done, you can merge my documentation to the master branch of the wiki git repo to make the documentation visible for everyone.

**Comment by VladRassokhin** [comment]
@ringods 
> but wouldn't want my investment in time to be wasted after you implement this
At least it would be used in tests, but separate page with description is ok for me.
Gave you 'collaborator' permissions. Feel free to edit wikis.

**Comment by mkuzmin** [comment]
before:
```
resource "tls_private_key" "ssh" {
  algorithm = "RSA"
}
```

after:
```
variable "algorithm" {
  default = "RSA"
}
resource "tls_private_key" "ssh" {
  algorithm = "${var.algorithm}"
}
```

**Comment by VladRassokhin** [comment]
[Here's](https://www.dropbox.com/s/56v9xeezxkhwubw/intellij-hcl-0.5.12.3.zip?dl=0) test version of plugin if you'd like to test new refactoring.
