### ISSUE TITLE
Add support for `consul_keys`

### ISSUE THREAD

**Issue by wjam** [VladRassokhin/intellij-hcl#51]
If a variable is defined as coming from Consul, the plugin currently marks the code as red.

Example:

``` hcl
provider "consul" {
}

data "consul_keys" "demo" {
  key {
    name = "example"
    path = "/a/path/to/a/value"
  }
  key {
    name = "second"
    path = "/a/path/to/another/value"
  }

}

resource "archive_file" "init" {
  type = "zip"
  source_content = "${data.consul_keys.demo.var.example}"
  source_content_filename = "demonstration.txt"
  output_path = "${path.module}/example.zip"
}

```

**Comment by VladRassokhin** [comment]
Do you mean `variable` in ` source_content = "${data.consul_keys.demo.var.example}"` marked red?

**Comment by wjam** [comment]
Yes, that's correct. More specifically, `example` in `${data.consul_keys.demo.var.example}` is red.

**Comment by VladRassokhin** [comment]
@wjam Is it true that `var.X` should be resolved only if `key { name='X' } ` is defined? Or Terraform allows to use anything after `var.`?

**Comment by wjam** [comment]
`key { name='X' }` must be defined before it can be used. Here is the error when trying to refer to something that hasn't been defined as a key.
```
Error creating plan: 1 error(s) occurred:

* Resource 'data.consul_keys.demo' does not have attribute 'var.example' for variable 'data.consul_keys.demo.var.example'
```

**Comment by VladRassokhin** [comment]
@wjam Thanks for details.
For now I've added 'data.consul_keys.X.var.Y' to ignore, so any 'Y' would be correct.
Would try to improve that later.
