### ISSUE TITLE
Some data variables are missing arn node

### ISSUE THREAD

**Issue by ronpeled** [VladRassokhin/intellij-hcl#54]
The auto complete is missing just a few little things: '.arn' for data type objects. Notice any other object types are just fine and include most everything needed. The plugin currently marks the 'arn' part in red and shows an error while terraform works well with this notation. 

`output "ssl_certificate_arn" {
  value = "${data.aws_acm_certificate.default.arn}"
}`

Please fix. Otherwise great plugin! saves lots of time!

**Comment by VladRassokhin** [comment]
Do you have defined somewhere data resource of type `aws_acm_certificate` with name `default`?
Or it's kind of shadow data resource provided if `aws` provider present?

**Comment by ronpeled** [comment]
Yes, exactly. I'm using this snippet of code in a different file that handles my ALB:

```
data "aws_acm_certificate" "default" {
  domain = "${var.ssl_domain}"
  statuses = ["ISSUED", "PENDING_VALIDATION"]
}
```

**Comment by VladRassokhin** [comment]
Thanks. `arn` was introduced in some recent version of Terraform, so plugin doesn't know about it. Next plugin version would have model from Terraform 0.8.0-rc1 (or even newer)
