### ISSUE TITLE
Valid escapes creating errors with quote detection

### ISSUE THREAD

**Issue by CrazyBS** [VladRassokhin/intellij-hcl#56]
I have several multi-line remote-exec statements in my Terraform configuration.  I need to end each line with an escaped back-slash, but the quote character right afterwards is not being detected by the syntax checking.

```HCL
      "docker service create \\",
      "  --constraint 'node.role == manager' --name mongo \\",
      "  --replicas 1 \\",
      "  --mount type=volume,destination=\"/data/db\" \\",
      "  --restart-max-attempts 5 \\",
      "  mongo:3",
```
All of the lines, but the last decide I don't have a closing quote.  If I execute this in Terraform, everything works as expected.  In order to make the IntelliJ plugin happy, I need to add a space after the escaped back-slash so the quote is correctly detected.

Please add support for correct quote detection in the presence of other escaped characters.  Even the wiki markdown in GitHub is detecting the quote.

**Comment by VladRassokhin** [comment]
Fixed in 0.5.12
