### ISSUE TITLE
self reported invalid inside of connection blocks

### ISSUE THREAD

**Issue by CrazyBS** [VladRassokhin/intellij-hcl#57]
${self.private_ip} is reporting invalid when used inside connection blocks, but works fine in Terraform.

```HCL
  connection {
    type = "ssh"
    user = "ubuntu"
    private_key = "${file(var.internal_private_key_path)}"
    host = "${self.private_ip}" # <--- Reporting Invalid

    bastion_host = "${aws_instance.bastion_az1.public_ip}"
    bastion_user = "ec2-user"
    bastion_private_key = "${file(var.bastion_private_key_path)}"
  }

  provisioner "remote-exec" { ... }
```

**Comment by VladRassokhin** [comment]
Seems documentation (quote below) is misleading. Actually both `provisioner` and `connection` blocks may have `self` references.
> -> **Note**: The `self.ATTRIBUTE` syntax is only allowed and valid within
provisioners.

**Comment by VladRassokhin** [comment]
As workaround you could disable inspection

**Comment by CrazyBS** [comment]
I wanted to ensure the bug was tracked.  It isn't blocking me.
