### ISSUE TITLE
Multiline and Slash broke after update

### ISSUE THREAD

**Issue by pkrbj** [VladRassokhin/intellij-hcl#58]
Hi,

This variable  was perfectly fine on IntelliJ and ran fine on terraform. But after the last update (HCL), intellij complains about syntax error in default.

**It worked fine in 0.5.10. No errors** 

```
variable "cms_beanstalk_enhanced_metric_json" {
  description = "Elastic Beanstalk Enhanced Metric JSON"
  default = "{
  \"CloudWatchMetrics\": {
    \"Environment\": {},
    \"Instance\": {}
  },
  \"Version\": 1
 }"
}
```

**Comment by VladRassokhin** [comment]
Latest plugin designed to work with Terraform 0.8 where multiline string literals are prohibited, except they are just interpolation. Consider use heredocs, e.g.
```
variable "cms_beanstalk_enhanced_metric_json" {
  description = "Elastic Beanstalk Enhanced Metric JSON"
  default = <<-EOL
  "CloudWatchMetrics": {
    "Environment": {},
    "Instance": {}
  },
  "Version": 1
  }
  EOL
}
```
