### ISSUE TITLE
Webstorm fails to install plugin

### ISSUE THREAD

**Issue by chmontgomery** [VladRassokhin/intellij-hcl#7]
I'm seeing the following error message when trying to install v0.2.3 from here: https://plugins.jetbrains.com/plugin/7808?pr=webStorm via Plugins > Install plugin from disk > select .zip file:

<img width="404" alt="screen shot 2015-07-22 at 4 02 02 pm" src="https://cloud.githubusercontent.com/assets/232356/8837284/39e60272-308b-11e5-9439-4e4de457e76c.png">

Here is my current version:

<img width="401" alt="screen shot 2015-07-22 at 4 02 27 pm" src="https://cloud.githubusercontent.com/assets/232356/8837293/42a8228c-308b-11e5-9b30-95fdca7eb438.png">

Is my version not supported? Is there an older version that would work? I don't have the option to upgrade to Webstorm v10.0 at this time.

**Comment by VladRassokhin** [comment]
For now minimum platform version is set to '141.0', your WebStorm 9 have '139.1112'.
As workaround you can manually modify `META-INF/plugin.xml` file inside `intellij-hcl.zip/intellij-hcl/lib/intellij-hcl.jar`.
Will test and downgrade minimum requirement in next release

**Comment by chmontgomery** [comment]
Setting to minimum version `139.0` seemed to work, thanks!

**Comment by chmontgomery** [comment]
I spoke too soon, I'm having problems with the plugin crashing in my environment. E.g., when I add a new string interpolation bracket, I get a plugin error and this happens to my src file view:

<img width="640" alt="screen shot 2015-07-24 at 4 00 05 pm" src="https://cloud.githubusercontent.com/assets/232356/8884573/4e5bd810-321d-11e5-87bb-c239f3bbd352.png">

**Comment by VladRassokhin** [comment]
Please try new version (0.2.5)

**Comment by chmontgomery** [comment]
Thanks! looks like everything is now working as expected (installed fine, no plugin crash, etc). Thanks for the quick response!
