### ISSUE TITLE
Terraform fmt on save

### ISSUE THREAD

**Issue by PeteGoo** [VladRassokhin/intellij-hcl#71]
It would be great to have the plugin run `terraform fmt` on saving of a file.

**Comment by stack72** [comment]
IMO that should be optional - the same way that Goglang has the ability so specify an action on save

**Comment by jen20** [comment]
Yup, the canonical `terraform fmt` style is particularly nasty, so making this optional would be a A Good Thing.

**Comment by matschaffer** [comment]
For the time being I've worked around this with the [file watchers plugin](https://plugins.jetbrains.com/plugin/7177-file-watchers) and the following config. Only been using it an hour or so, but seems to work okay so far.

![screen shot 2017-04-12 at 9 25 00](https://cloud.githubusercontent.com/assets/690/24936168/f005951a-1f61-11e7-9f34-78789f9f33d0.png)

**Comment by VladRassokhin** [comment]
I've added separate action like it's done in Gogland. 
There's no plan to automatically run 'terraform fmt' on save, though there's checkbox in commit dialog available which would run `terraform fmt` automatically on all changed files upon commit.

**Comment by danielcompton** [comment]
Would you reconsider this? Gogland has an option to format on save: https://stackoverflow.com/a/42169265/826486. I personally find it much more useful to have format on save, as things are always formatted correctly. I don't use the IntelliJ VCS client, so the format on commit options there aren't so helpful.

![](https://i.stack.imgur.com/3bDGd.png)

**Comment by VladRassokhin** [comment]
@danielcompton I'll think about that. If it's easy to do - will do. Anyway contributions are welcome.

**Comment by VladRassokhin** [comment]
@danielcompton Actually in latest GoLand EAP 18 they deprecated such feature... and migrated to pre-defined template for FileWatchers. Will investigate that.
![goland eap 18 onsave](https://user-images.githubusercontent.com/552079/32863043-39a594a4-ca6b-11e7-9e70-63bf1ed11035.png)

![goland eap 18 filewatchers](https://user-images.githubusercontent.com/552079/32863042-397fcb02-ca6b-11e7-9674-418a5e3ff8fb.png)

![goland eap 18 filewatcher config](https://user-images.githubusercontent.com/552079/32863041-3956decc-ca6b-11e7-9322-bf5292f55f22.png)

**Comment by VladRassokhin** [comment]
Fixed, now it's recommended to install 'File Watchers' plugin and configure one from `terraform fmt` template

**Comment by VladRassokhin** [comment]
FYI 0.6.9 with 'FileWatcher' template just released.

**Comment by matschaffer** [comment]
Also seems to work nicely! 👍


-Mat

matschaffer.com
