### ISSUE TITLE
Resource ignition_systemd_unit content not required

### ISSUE THREAD

**Issue by darrenswhite** [VladRassokhin/intellij-hcl#72]
When using the Ignition provider to create a systemd unit resource, if the content property is missing, a warning is shown. This should not be the case as content is optional.

Example:

```
resource "ignition_systemd_unit" "my_service" {
  name    = "my_service.service"
  mask    = true
}
```

Edit: the same happens when dropin is present and content is not.

**Comment by VladRassokhin** [comment]
That was changed in Terraform v0.8.5, though current version of HCL plugin uses meta-information from Terraform v0.8.4. Would be fixed in next update.

**Comment by VladRassokhin** [comment]
I've uploaded version 0.5.12.2 to plugins repo, please update plugin in your IDE.
