### ISSUE TITLE
Custom path for external Terraform plugin *.json descriptors

### ISSUE THREAD

**Issue by maxmanuylov** [VladRassokhin/intellij-hcl#75]
I use several external (non-default) Terraform plugins. I generated `*.json` descriptors for all of them to have correct highlighting in my project and put them to this directory:
```
~/Library/Application Support/Gogland1.0/intellij-hcl/classes/terraform/model/providers/*.json
```

Everything works fine until I update the `intellij-hcl` plugin or update an IDE to the next major release, so I lose all my custom plugin descriptors.

It would be cool to specify a custom path for external plugin descriptors to not lose them on updates.

**Comment by VladRassokhin** [comment]
Plugin now also reads schemas from `~/.terraform.d/schemas/*.json` files on Linux/OSX and `%APPDATA%/terraform.d/schemas/*.json` on Windows.
