### ISSUE TITLE
terraform plugin structure support

### ISSUE THREAD

**Issue by sopak** [VladRassokhin/intellij-hcl#78]
Hi,
your plugin is really good.
It would be really nice and useful to have on the fly (cached) import of the terraform plugin model.
For example by using specific URL in the plugin configuration.

**Comment by VladRassokhin** [comment]
Hi,
What do you mean in ' terraform plugin model'?
Would you like to have completion and validation for your custom plugin?

**Comment by sopak** [comment]
yes, I would like to have completion and validation for custom plugins. Some easy way  to add  my model
as  defined here: https://github.com/VladRassokhin/intellij-hcl/tree/7c27594c1e09dc9b9c8b2d32b9fde9d69bbcf97d/res/terraform/model

**Comment by VladRassokhin** [comment]
Latest plugin would read schemas (in format like `res/terraform/model/*json` files) from `~/.terraform.d/schemas/*.json`
See commit 3a8156e4f80751779f6638bef9cc81de4fc91209 for details

**Comment by VladRassokhin** [comment]
I'm closing issue for now as there's ability to read external schemas. If i've missed something - please reopen it or open new one.

**Comment by sopak** [comment]
OK,  I will try it and  let you know ;) thank you
