### ISSUE TITLE
data "template_file" doesn't get auto complete

### ISSUE THREAD

**Issue by kitsunde** [VladRassokhin/intellij-hcl#82]
The `template_file` data source doesn't seem to exist.

<img width="195" alt="screenshot 2017-04-18 00 16 55" src="https://cloud.githubusercontent.com/assets/48965/25095025/59fd7050-23cc-11e7-834e-7b64fcc94521.png">

**Comment by VladRassokhin** [comment]
Seems fix for #77 isn't so safe.
As workaround try invoking completion three times. ;)

**Comment by VladRassokhin** [comment]
Would be available in next plugin update.
