### ISSUE TITLE
`vpc_zone_identifier` missing in `aws_autoscaling_group`

### ISSUE THREAD

**Issue by Dominik-K** [VladRassokhin/intellij-hcl#84]
`vpc_zone_identifier` does not show up in the [autocompletion list](https://www.jetbrains.com/help/idea/2017.1/auto-completing-code.html) in the `aws_autoscaling_group`.

Instead `vpc_classic_link_id` and `vpc_classic_link_security_groups` are listed, even if they are not in the [Terraform doc](https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html) and in the plugins [ `aws.json`resource code](https://github.com/VladRassokhin/intellij-hcl/blob/master/res/terraform/model/providers/aws.json#L4864) anymore.

Tried it with the new version 0.6.1 (PyCharm CE 2017.1.1)

**Comment by VladRassokhin** [comment]
Cannot reproduce with 0.6.1 in given file:
```tf

resource "aws_autoscaling_group" "asas" {
  availability_zones = ['a']

  launch_configuration = ""
  max_size = 0
  min_size = 0
<caret>
}
```
Please attach simple terraform config where problem is reproducible.

**Comment by Dominik-K** [comment]
Hmm, I tried it again and now it works as intended. Maybe PyCharm was not correctly restarted. Sorry for the interruption.
