### ISSUE TITLE
Support results from external data sources

### ISSUE THREAD

**Issue by gnarea** [VladRassokhin/intellij-hcl#85]
Terraform supports so-called [External Data Sources](https://www.terraform.io/docs/providers/external/data_source.html), which expose the attribute `result` as a map whose key/value pairs are determined at runtime.

At the moment, any reference to a key in the `result` attribute leads to an error in the editor ("Unresolved reference <KEY_NAME>").

I think it'd be great if this were not reported as an error (or warning). Ideally, this plugin would calculate the keys (e.g., by running `terraform console`), but I'm sure that'd be much more time-consuming to implement, so I think simply suppressing the error would be enough for those of us who find it distracting to see errors we can't fix in our source code.

**Comment by VladRassokhin** [comment]
Done simple fix: anything could be resolved from 'result'

**Comment by gnarea** [comment]
Thank you so much, @VladRassokhin! Keep up the good work.
