### ISSUE TITLE
Error parsing maps vars

### ISSUE THREAD

**Issue by lemaral** [VladRassokhin/intellij-hcl#86]
Eg when showing "${var.network.["availability_zones"]}"
the .[ are red underlined and tooltip is showing:
<expression> expected, got '['
Many thanks for your good work :)

**Comment by VladRassokhin** [comment]
Correct syntax is `${var.network["availability_zones"]}`
For some reason Terraform supports weird variant. I'd better not fix that in plugin.

**Comment by lemaral** [comment]
Thank you, you are right, just figured it out too. I will fix this on my side :)
Best regards
Alex.
