### ISSUE TITLE
unknown block type 'backend' in terraform definition

### ISSUE THREAD

**Issue by kobymeir-reposify** [VladRassokhin/intellij-hcl#87]
I'm using plugin version 0.6.2 in PyCharm 2017.1.2 with Terraform 0.9.4 and i'm getting a syntax error:
unknown block type 'backend' 
but terraform is ok with this configuration

```HCL
terraform {
  required_version = "0.9.4"

  backend "s3" {
    bucket     = "terraform.state"
    region     = "us-east-1"
    lock_table = "terraform.state"
  }
}
```

**Comment by kobymeir-reposify** [comment]
@VladRassokhin thanks for the fix, one small thing, i'm getting this message 'missing required properties: key' , but it's not entirely mandatory as it can be populated externally from the command line to terraform using `-backend-config='key=something'` to terraform init, and in general the backend block is valid without any field in it

**Comment by VladRassokhin** [comment]
Thanks for testing and noting about 'required' properties, would do something about that in next version.
