### ISSUE TITLE
google_compute_instance's assigned_nat_ip considered unresolved

### ISSUE THREAD

**Issue by matschaffer** [VladRassokhin/intellij-hcl#89]
It looks like the (somewhat long-winded) way to get the external IP of a google compute instance in terraform is:

```hcl
google_compute_instance.node.network_interface.0.access_config.0.assigned_nat_ip
```

But this is considered an unresolved reference in the IntelliJ HCL plugin:

<img width="382" alt="screen shot 2017-05-26 at 15 25 16" src="https://cloud.githubusercontent.com/assets/690/26483363/93b5fe56-4227-11e7-85ce-73e5c0061e2d.png">

Would be nice to get it recognized since terraform (tested in 0.9.5) recognizes it just fine.

**Comment by matschaffer** [comment]
Hm... so I'm running 0.6.3 here which looks like should have `assigned_nat_ip` defined in https://github.com/VladRassokhin/intellij-hcl/blob/v0.6.3/res/terraform/model/providers/google.json#L3191

**Comment by matschaffer** [comment]
Weird. There's even [a test for it](https://github.com/VladRassokhin/intellij-hcl/blob/v0.6.3/test/org/intellij/plugins/hcl/terraform/TerraformModelProviderTest.java#L46) - I tried invalidating caches and restarting but it still shows up red.

Any idea what I might have wrong?

**Comment by VladRassokhin** [comment]
Hi @matschaffer 
Sorry for not answering for so long. 
How `resource "google_compute_instance" "node"` is defined?
Do you have `network_interface` and `access_config` blocks there?

**Comment by matschaffer** [comment]
No worries :) Thanks for getting back to me.

We have `network_interface` and `access_config` in there. The `access_config` is blank to pick up an auto-assigned IP.

Here's a mostly-redacted version of the file that's showing the warning:

![node_tf_-_cloud_-____elastic_cloud_](https://user-images.githubusercontent.com/690/28318262-15fddd46-6c05-11e7-835b-f407ca910e7d.png)

**Comment by VladRassokhin** [comment]
AFAIK defining access config as block, not property with 'object' solves problem, e.g.
```hcl
network_interface {
    access_config {}
  }
```

**Comment by VladRassokhin** [comment]
Anyway, I've fixed that and it would work both ways in next plugin release
