### ISSUE TITLE
Support hexadecimal number literal

### ISSUE THREAD

**Issue by maemichi-monosense** [VladRassokhin/intellij-hcl#90]
Terraform (v0.9) supports number literal for hexadecimal numbers, and it is documented in syntax section: https://www.terraform.io/docs/configuration/syntax.html#terraform-syntax

But the current version (0.6.3) treats it as illegal.

It would be great if the plugin supports it.

```HCL
123 # valid
0xFF # should be valid, too
```

**Comment by VladRassokhin** [comment]
Thanks for reporting. Actually plugin supports such numbers, however 'illegal number' erroneously reports some hexadecimal numbers. Fixed regexp.
