### ISSUE TITLE
Add support for nested interpolation

### ISSUE THREAD

**Issue by shorn** [VladRassokhin/intellij-hcl#95]
In order to make my code readable when dealing with extremely long lines, I like to use a combination of join() and list() functions to format the configuration code into multiple lines, like so:

```
data "template_file" "prefix-template" {
  template = "${file("server-scripts/prefix-server-provision.sh")}"
  vars {
    TF_APP_LOG_GROUP = "${<caret1>aws_cloudwatch_log_group.prefix-loggroup.name}"
    TF_APP_SSM_PARAMS = "${
      join(
        " ",
        list(
          "${<caret2>aws_ssm_parameter.prefix-docker-image-param.name}",
          "${aws_ssm_parameter.prefix-db-url-param.name}",
          "${aws_ssm_parameter.prefix-db-user-param.name}",
          "${aws_ssm_parameter.prefix-db-password-secure-param.name}",
          "${aws_ssm_parameter.prefix-mia-passwords-secure-param.name}",
          "${aws_ssm_parameter.prefix-domain-param.name}",
          "${aws_ssm_parameter.prefix-issuer-param.name}",
          "${aws_ssm_parameter.prefix-client-id-param.name}",
          "${aws_ssm_parameter.prefix-client-secret-secure-param.name}"
        )
      )
    }"
  }
}
``` 

The HCL plugin understands this construct enough to know that it's not an error, but the plugin doesn't currently do auto-completion on the variable references inside the list.

Any chance this could be added? 
(I understand it might be a pretty hefty change)

EDIT: added <caret> markers are requested.

**Comment by VladRassokhin** [comment]
Thanks for reporting, could you please mark with `<caret>` place where do you expect variables completion to appear?

**Comment by shorn** [comment]
Updated the original exampe with `<caret1>` and `<caret2>`.
If you put your cursor at `<caret1>` and press `ctrl-space` you will get a popup completion list giving all TF resources in the project.
If cursor is at `<caret2>` and press `ctrl-space` nothing will happen.

Also note that the variable expression in TF_APP_LOG_GROUP is white, but all the variable expressions in TF_APP_SSM_PARAMS are green.
![image](https://user-images.githubusercontent.com/216456/27616753-5ec2e37a-5bf5-11e7-94dc-979dd6194ef4.png)

**Comment by shorn** [comment]
Oops, forgot to add the <caret> markes to the original issue. 
Now added.

**Comment by VladRassokhin** [comment]
Thanks.

// Dev log:
Simple approach to inject one interpolation into another failed, would try to improve completion providers.

**Comment by shorn** [comment]
Thought it might be tricky - appreciate the feedback.

Might be worth checking with Hashicorp folks that this functionality is actually intended to work.
I asked on the Google group, but no response: [https://groups.google.com/forum/#!topic/terraform-tool/D9-kZZI-QwI](https://groups.google.com/forum/#!topic/terraform-tool/D9-kZZI-QwI)

Keep up the great work - HCL plugin is super-helpful!

**Comment by VladRassokhin** [comment]
Thanks for kind words.

Have you tried another approach: no quotes on parameters?, like
```
join(
        " ",
        list(
          ${aws_ssm_parameter.prefix-docker-image-param.name},
          ${aws_ssm_parameter.prefix-db-url-param.name},
        )
      )
```

**Comment by shorn** [comment]
Your approach didn't work for me I got a TF error `Unknown token: 176:18 IDENT join`.
This is what I tried, is that what you meant?
```
data "template_file" "sto-test" {
  template = "blah"
  vars {
    TEST_PARAM = join(
      " ",
      list(
        ${aws_ssm_parameter.awsgui-svc-int-docker-image-param.name},
        ${aws_ssm_parameter.awsgui-svc-int-db-url-param.name}
      )
    )
  }
}
```

But anyway, this does work:
```
data "template_file" "sto-test" {
  template = "blah"
  vars {
    TEST_PARAM = "${
      join(
        " ",
        list(
          aws_ssm_parameter.awsgui-svc-int-docker-image-param.name,
          aws_ssm_parameter.awsgui-svc-int-db-url-param.name
        )
      )
    }"  
  }
}
```
The outer string and variable interpolation seem to be needed, then the internal variables have to be done without variable interpolation.

The HCL plugin works fully with this - completion, syntax coloring, etc.
Thanks for your help!

I'm happy to close this issue since I've got the functionality I wanted.

**Comment by VladRassokhin** [comment]
Fine, thank for reporting.
