### ISSUE TITLE
Installing HCL plugin in IntelliJ fails since latest changes to this repo

### ISSUE THREAD

**Issue by BogdanSorlea** [VladRassokhin/intellij-hcl#97]
I've basically uninstalled and reinstalled the HCL plugin but on reinstall it fails with the following error dialog (note that it fails even while loading the list of plugins, without issuing any install action)...

![intellij_error](https://user-images.githubusercontent.com/4004804/28569728-c535349c-7143-11e7-89c1-92a7ffbdee95.jpg)

**Comment by VladRassokhin** [comment]
Seems you've added sources url to 'Custom Plugin Repositories' list in IDE settings.
To install plugin just find it in `Settings -> Plugins - > Browse repositories`
